# Generated by Django 4.2.2 on 2023-07-18 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateField(
                db_index=True,
                default=datetime.datetime(
                    2023, 7, 18, 9, 4, 46, 482440, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
