# Generated by Django 4.2.2 on 2023-07-18 10:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_alter_payment_payment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
