# Generated by Django 4.2.2 on 2023-06-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('is_weekend', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('country', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['country'], name='core_holida_country_a15e92_idx')],
            },
        ),
    ]
