# Generated by Django 4.2.2 on 2023-06-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['date'], name='core_holida_date_6cc7ce_idx'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['is_weekend'], name='core_holida_is_week_c16818_idx'),
        ),
    ]
