# Generated by Django 4.2.2 on 2023-06-09 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_holiday_core_holida_date_6cc7ce_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('date', 'country')},
        ),
    ]
