# Generated by Django 4.2.2 on 2023-06-19 01:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_holiday_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "alpha2_code",
                    models.CharField(db_index=True, max_length=2, unique=True),
                ),
                (
                    "alpha3_code",
                    models.CharField(db_index=True, max_length=3, unique=True),
                ),
                (
                    "numeric_code",
                    models.CharField(db_index=True, max_length=3, unique=True),
                ),
            ],
            options={
                "ordering": ["country"],
            },
        ),
    ]
