# Generated by Django 5.2.4 on 2025-12-05 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_countrycode_id_alter_countrycode_alpha3_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="countrycode",
            name="country_idn",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, null=True
            ),
        ),
    ]
