# Generated by Django 4.2.2 on 2023-06-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_countrycode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holiday",
            name="country",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="holiday",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
