# Generated by Django 6.0.1 on 2026-01-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ocr_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrjob',
            name='traceback',
            field=models.TextField(blank=True),
        ),
    ]
