# Generated by Django 4.2.2 on 2023-07-03 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0002_alter_invoice_options_alter_invoice_due_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceapplication",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_applications",
                to="invoices.invoice",
            ),
        ),
    ]
