# Generated by Django 4.2.2 on 2023-07-04 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0004_invoice_created_at_invoice_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="invoice_application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="invoices.invoiceapplication",
            ),
        ),
    ]
