# Generated by Django 4.2.2 on 2023-07-07 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_customer_active"),
        ("invoices", "0005_alter_payment_invoice_application"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceapplication",
            name="paid_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
