# Generated by Django 4.2.2 on 2023-07-13 00:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "invoices",
            "0007_alter_invoiceapplication_options_payment_created_at_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoiceapplication",
            old_name="due_amount",
            new_name="amount",
        ),
    ]
