# Generated by Django 4.2.2 on 2023-07-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0008_rename_due_amount_invoiceapplication_amount"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="invoiceapplication",
            constraint=models.UniqueConstraint(
                fields=("customer_application", "invoice"),
                name="unique_invoice_application",
            ),
        ),
    ]
