# Generated by Django 4.2.2 on 2023-07-15 00:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0009_invoiceapplication_unique_invoice_application"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoiceapplication",
            name="paid_amount",
        ),
        migrations.RemoveField(
            model_name="invoiceapplication",
            name="payment_status",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
