# Generated by Django 4.2.2 on 2023-07-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0010_remove_invoiceapplication_paid_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("partial_payment", "Partial Payment"),
                    ("paid", "Paid"),
                    ("overdue", "Overdue"),
                    ("disputed", "Disputed"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                    ("write_off", "Write Off"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
