# Generated by Django 4.2.2 on 2023-07-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0011_invoiceapplication_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default="0", max_digits=12),
        ),
    ]
