# Generated by Django 4.2.2 on 2023-07-20 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=50, unique=True)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("has_ocr_check", models.BooleanField(default=False)),
                ("has_expiration_date", models.BooleanField(default=False)),
                ("has_doc_number", models.BooleanField(default=False)),
                ("has_file", models.BooleanField(default=False)),
                ("has_details", models.BooleanField(default=False)),
                ("validation_rule_regex", models.CharField(blank=True, max_length=500)),
                ("is_in_required_documents", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("code", models.CharField(db_index=True, max_length=20, unique=True)),
                ("description", models.TextField(blank=True, db_index=True)),
                (
                    "immigration_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[("visa", "Visa"), ("other", "Other")],
                        db_index=True,
                        default="other",
                        max_length=50,
                    ),
                ),
                ("validity", models.PositiveIntegerField(blank=True, null=True)),
                ("required_documents", models.CharField(blank=True, max_length=1024)),
                ("optional_documents", models.CharField(blank=True, max_length=1024)),
                (
                    "documents_min_validity",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step", models.PositiveIntegerField(db_index=True)),
                ("last_step", models.BooleanField(db_index=True, default=False)),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("duration", models.PositiveIntegerField(db_index=True, default=0)),
                ("duration_is_business_days", models.BooleanField(default=True)),
                (
                    "notify_days_before",
                    models.PositiveIntegerField(blank=True, default=0),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["step"],
                "unique_together": {("product", "step")},
            },
        ),
    ]
