# Generated by Django 6.0.2 on 2026-02-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_task_add_task_to_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notify_customer',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
