# Generated by Django 6.0.2 on 2026-02-23 04:43

from decimal import Decimal

from django.conf import settings
from django.db import migrations, models
from django.db.models.functions import Coalesce


def populate_retail_price(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    Product.objects.filter(retail_price__isnull=True).update(
        retail_price=Coalesce("base_price", models.Value(Decimal("0.00")))
    )


def reverse_populate_retail_price(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    Product.objects.update(retail_price=models.F("base_price"))


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_task_notify_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.RunPython(
            code=populate_retail_price,
            reverse_code=reverse_populate_retail_price,
        ),
        migrations.AlterField(
            model_name='product',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('base_price__isnull', True), ('retail_price__gte', models.F('base_price')), _connector='OR'), name='product_retail_price_gte_base_price'),
        ),
    ]
