# Generated by Django 6.0.2 on 2026-02-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_documenttype_ai_validation_rename_and_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='deprecated',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='deprecated',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
