# Generated by Django 6.0.2 on 2026-02-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_documenttype_deprecated_product_deprecated'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='is_stay_permit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='application_window_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
