# Generated by Django 6.0.2 on 2026-02-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_documenttype_is_stay_permit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttype",
            name="expiring_threshold_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
