# Generated by Django 6.0.2 on 2026-03-03 07:54

import django.core.validators
import products.models.product
from django.db import migrations, models


def set_existing_products_currency_to_idr(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    Product.objects.all().update(currency="IDR")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_uses_customer_app_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(default=products.models.product.default_product_currency, max_length=3, validators=[django.core.validators.RegexValidator(message='Currency must be a 2 or 3-letter code (e.g. IDR, USD, EUR).', regex='^[A-Za-z]{2,3}$')]),
        ),
        migrations.RunPython(set_existing_products_currency_to_idr, noop_reverse),
    ]
