# Generated by Django 6.0.3 on 2026-03-10 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_category'),
        ('products', '0016_product_price_history'),
    ]

    operations = [
    ]
