"""
Django settings for business_suite project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import logging
import os
from pathlib import Path

from dotenv import load_dotenv
from peewee import PostgresqlDatabase

from core.utils.dropbox_refresh_token import refresh_dropbox_token

# Load environment variables from .env file
load_dotenv()


# MOCK AUTH SETTINGS
def _parse_bool(value, default=False):
    if value is None:
        return default
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() in {"true", "1", "yes", "y", "on"}


def _parse_list(value, default=None):
    if value is None:
        return default if default is not None else []
    items = [item.strip() for item in str(value).split(",")]
    return [item for item in items if item]


MOCK_AUTH_ENABLED = _parse_bool(os.getenv("MOCK_AUTH_ENABLED", "False"))
MOCK_AUTH_USERNAME = os.getenv("MOCK_AUTH_USERNAME", "mockuser")
MOCK_AUTH_EMAIL = os.getenv("MOCK_AUTH_EMAIL", "mock@example.com")
MOCK_AUTH_IS_SUPERUSER = _parse_bool(os.getenv("MOCK_AUTH_IS_SUPERUSER", "True"))
MOCK_AUTH_IS_STAFF = _parse_bool(os.getenv("MOCK_AUTH_IS_STAFF", "True"))
MOCK_AUTH_GROUPS = _parse_list(os.getenv("MOCK_AUTH_GROUPS", "admin"))
MOCK_AUTH_ROLES = _parse_list(os.getenv("MOCK_AUTH_ROLES", "admin"))

GLOBAL_SETTINGS = {
    "SITE_NAME": os.getenv("SITE_NAME", "Business Suite"),
    "SITE_DESCRIPTION": os.getenv(
        "SITE_DESCRIPTION",
        "Comprehensive ERP for service agencies: CRM, catalog, applications, invoicing, payments, document management.",
    ),
    "DOCUMENT_EXPIRATION_NOTIFICATION_DAYS": 180,
    "LOGO_FILENAME": os.getenv("LOGO_FILENAME", "logo_transparent.png"),
    "LOGO_INVERTED_FILENAME": os.getenv("LOGO_INVERTED_FILENAME", "logo_inverted_transparent.png"),
}

# Invoice Import Settings
INVOICE_IMPORT_MAX_WORKERS = int(os.getenv("INVOICE_IMPORT_MAX_WORKERS", "3"))  # Max parallel imports

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
APP_DOMAIN = os.getenv("APP_DOMAIN")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "False") == "True"

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "[::1]",
    os.getenv("APP_DOMAIN", ""),
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "core.apps.CoreConfig",
    "landing",
    "customers",
    "products",
    "invoices.apps.InvoicesConfig",
    "payments",
    "customer_applications",
    "letters",
    "reports",
    "corsheaders",
    "rest_framework",
    "drf_spectacular",
    "rest_framework.authtoken",
    "widget_tweaks",
    "nested_admin",
    "crispy_forms",
    "crispy_bootstrap5",
    "django.contrib.humanize",
    "django_unicorn",
    "debug_toolbar",
    "dbbackup",
    "storages",
    "admin_tools",
    "django_cleanup.apps.CleanupConfig",
    "django_user_agents",
    "huey.contrib.djhuey",
]

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # to serve static files
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # 'business_suite.middleware.DisableCsrfCheck',  # Your custom middleware
    "business_suite.middlewares.AuthLoginRequiredMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    # it merge all changes of object per request
    "django_user_agents.middleware.UserAgentMiddleware",
    "core.middleware.performance_logger.PerformanceLoggingMiddleware",
]


ROOT_URLCONF = "business_suite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.request",
                "business_suite.context_processors.site_info",
            ],
        },
    },
]

WSGI_APPLICATION = "business_suite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": os.path.join(BASE_DIR, "files/db.sqlite3"),
#     }
# }
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASS"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
        # Connection pooling - keep connections alive for 600 seconds
        "CONN_MAX_AGE": 600,
        # Connection pool size per worker
        "CONN_HEALTH_CHECKS": True,
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Singapore"

USE_I18N = True

USE_TZ = True

# Configure project locale path for translations (locale is at project root, one level up from BASE_DIR)
LOCALE_PATHS = [os.path.join(BASE_DIR, "..", "locale")]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

#
# STEF
#


# by default, all views require login. To allow anonymous access, add the view name to UNAUTHENTICATED_URLS
LOGIN_URL = "/login/"
LOGOUT_URL = "/logout/"
LOGIN_EXEMPT_URLS = (
    r"^login/$",
    r"^logout/$",
    r"^api/.*$",  # match 'api/' and any subpaths
    r"^api-token-auth/$",
)

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login"

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_DOMAIN = APP_DOMAIN
SESSION_COOKIE_DOMAIN = APP_DOMAIN
CSRF_TRUSTED_ORIGINS = [
    f"https://{APP_DOMAIN}",
    f"https://www.{APP_DOMAIN}",
    f"https://{APP_DOMAIN}",
    "https://localhost",
    "http://localhost",
    "http://localhost:4200",
]
SESSION_COOKIE_SAMESITE = "Lax"  # Changed from "None" - use Lax for same-site Django apps
CSRF_COOKIE_SAMESITE = "Lax"  # Changed from "None"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "business_suite.authentication.JwtOrMockAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        # 'rest_framework.permissions.IsAuthenticated', #the one below is more granular
        "rest_framework.permissions.DjangoModelPermissions",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "djangorestframework_camel_case.render.CamelCaseJSONRenderer",
        "djangorestframework_camel_case.render.CamelCaseBrowsableAPIRenderer",
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "djangorestframework_camel_case.parser.CamelCaseJSONParser",
        "djangorestframework_camel_case.parser.CamelCaseFormParser",
        "djangorestframework_camel_case.parser.CamelCaseMultiPartParser",
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
        "rest_framework.parsers.FileUploadParser",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "EXCEPTION_HANDLER": "api.utils.exception_handler.custom_exception_handler",
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/day",
        "user": "1000/day",
        "quick_create": "20/minute",
        "cron": "5/minute",
        "ocr": "10/minute",
        "ocr_status": "120/minute",
        "document_ocr": "10/minute",
        "document_ocr_status": "120/minute",
    },
}

SPECTACULAR_SETTINGS = {
    "TITLE": "BusinessSuite API",
    "DESCRIPTION": "API for BusinessSuite ERP/CRM",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "CAMELIZE_NAMES": True,
    "COMPONENT_SPLIT_PATCH": False,
}

# in case we want to try using nodejs for the frontend
CORS_ORIGIN_WHITELIST = ["http://localhost:3000", "http://localhost:4200"]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# https://github.com/legion-an/django-models-logging
LOGGING_MODELS = (
    # 'app.ClassName',      # logging only for this model
    "customers",  # logging of all models in this app
    "products",
    "invoices",
    "customer_applications",
)

SESSION_SAVE_EVERY_REQUEST = True

# This is for the debug toolbar when using docker
# https://docs.djangoproject.com/en/3.2/ref/settings/#internal-ips
# if DEBUG:
#     import socket  # only if you haven't already imported this
#     hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
#     INTERNAL_IPS = [ip[: ip.rfind(".")] + ".1" for ip in ips] + ["127.0.0.1", "10.0.2.2"]


CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        # "LOCATION": "unique-snowflake",
    },
    "select2": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    },
}

HUEY = {
    "huey_class": "huey.contrib.sql_huey.SqlHuey",
    "name": "business_suite",
    "results": True,
    "store_errors": True,
    "immediate": False,
    "database": PostgresqlDatabase(
        os.getenv("DB_NAME"),
        user=os.getenv("DB_USER"),
        password=os.getenv("DB_PASS"),
        host=os.getenv("DB_HOST") or "localhost",
        port=int(os.getenv("DB_PORT")) if os.getenv("DB_PORT") else 5432,
    ),
    "consumer": {
        "workers": int(os.getenv("HUEY_WORKERS", "2")),
        "worker_type": os.getenv("HUEY_WORKER_TYPE", "thread"),
        "scheduler_interval": 1,
        "check_worker_health": True,
        "health_check_interval": 1,
    },
}

# select2
SELECT2_CACHE_BACKEND = "select2"

USER_AGENTS_CACHE = "default"

# SESSION_ENGINE = "django.contrib.sessions.backends.cache"
# # SESSION_COOKIE_AGE = 60 * 60 * 24  # One day
# SESSION_COOKIE_AGE = 60 * 5 # 5 minutes

TESSERACT_CMD = "/opt/homebrew/bin/tesseract"


# Settings for Django static and media files
DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
MEDIA_ROOT = os.path.join(BASE_DIR, "files/media/")
MEDIA_URL = "/uploads/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATIC_SOURCE_ROOT = os.path.join(BASE_DIR, "static")

DOCUMENTS_FOLDER = "documents"
APPLICATION_DEFAULT_FILES_FOLDER = "application_default_files"
TMPFILES_FOLDER = "tmpfiles"


def get_dropbox_token():
    # Skip token refresh in development to avoid network issues
    if os.getenv("DJANGO_DEBUG", "False") == "True":
        return None
    try:
        return refresh_dropbox_token(
            os.getenv("DROPBOX_APP_KEY"),
            os.getenv("DROPBOX_APP_SECRET"),
            os.getenv("DROPBOX_OAUTH2_REFRESH_TOKEN"),
        )
    except Exception as e:
        # Log the error and return None to allow Django to start
        import logging

        logger = logging.getLogger(__name__)
        logger.error(f"Failed to refresh Dropbox token: {e}")
        return None


# Storage configuration
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
    "dbbackup": {
        "BACKEND": "storages.backends.dropbox.DropBoxStorage",
        "OPTIONS": {
            "oauth2_access_token": get_dropbox_token(),
            "app_key": os.getenv("DROPBOX_APP_KEY"),
            "app_secret": os.getenv("DROPBOX_APP_SECRET"),
        },
    },
}

# Folders to exclude from media backup
DBBACKUP_EXCLUDE_MEDIA_FODERS = ["tmpfiles"]

FULL_BACKUP_SCHEDULE = "02:00"
CLEAR_CACHE_SCHEDULE = ["03:00"]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "filters": {
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
            "filters": ["require_debug_true"],
        },
        "file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "logs") + "debug.log",
        },
        # "mail_admins": {
        #     "level": "ERROR",
        #     "class": "django.utils.log.AdminEmailHandler",
        #     "filters": ["special"],
        # },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "passport_ocr": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
        # "django.request": {
        #     "handlers": ["mail_admins"],
        #     "level": "ERROR",
        #     "propagate": False,
        # },
        # requires the PerformanceLoggingMiddleware to be added to MIDDLEWARE
        "performance": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

CURRENCY = "IDR"
CURRENCY_SYMBOL = "Rp"
CURRENCY_DECIMAL_PLACES = 0

# OpenAI API configuration for invoice import
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
OPENROUTER_API_BASE_URL = os.getenv("OPENROUTER_API_BASE_URL", "https://openrouter.ai/api/v1")

# LLM Provider: "openrouter" for multi-provider access, "openai" for direct OpenAI API
LLM_PROVIDER = os.getenv("LLM_PROVIDER", "openrouter")
LLM_DEFAULT_MODEL = os.getenv("LLM_DEFAULT_MODEL", "google/gemini-2.5-flash-lite")

DOCX_INVOICE_TEMPLATE_NAME = os.getenv("DOCX_INVOICE_TEMPLATE_NAME", "invoice_template_with_footer.docx")
DOCX_PARTIAL_INVOICE_TEMPLATE_NAME = os.getenv(
    "DOCX_PARTIAL_INVOICE_TEMPLATE_NAME", "partial_invoice_template_with_footer.docx"
)
DOCX_SURAT_PERMOHONAN_PERPANJANGAN_TEMPLATE_NAME = os.getenv(
    "DOCX_SURAT_PERMOHONAN_PERPANJANGAN_TEMPLATE_NAME", "surat_permohonan_perpanjangan.docx"
)

# Document Type Hooks Settings
# Path to the default sponsor passport file (relative to MEDIA_ROOT)
DEFAULT_SPONSOR_PASSPORT_FILE_PATH = os.getenv(
    "DEFAULT_SPONSOR_PASSPORT_FILE_PATH", "default_documents/default_sponsor_document.pdf"
)

# default language for generated documents
DEFAULT_DOCUMENT_LANGUAGE_CODE = os.getenv("DEFAULT_DOCUMENT_LANGUAGE_CODE", "id")

DEFFAULT_CUSTOMER_EMAIL = os.getenv("DEFFAULT_CUSTOMER_EMAIL", "sample_email@gmail.com")

# Python 3.14+ Logging Performance Optimizations
# Disable gathering of thread, process, and asyncio information to reduce overhead
logging.logThreads = False
logging.logProcesses = False
logging.logMultiprocessing = False
logging.logAsyncioTasks = False
