"""
Django settings for business_suite project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from .base import *

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [APP_DOMAIN, f"www.{APP_DOMAIN}", f"{APP_DOMAIN}", "bs-cron", "bs-core"]

MEDIA_ROOT = "/media/"

STATIC_ROOT = "/staticfiles/"

TESSERACT_CMD = "/usr/bin/tesseract"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "filters": {
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
            # "filters": ["require_debug_true"],
        },
        "file": {
            "class": "logging.FileHandler",
            "filename": "/logs/django.log",
            "formatter": "verbose",
        },
        # "mail_admins": {
        #     "level": "ERROR",
        #     "class": "django.utils.log.AdminEmailHandler",
        #     "filters": ["special"],
        # },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        # Suppress noisy Dropbox SDK logging
        "dropbox": {
            "handlers": ["file"],  # Only log to file, not console
            "level": "WARNING",  # Only show warnings and errors
            "propagate": False,
        },
        # Suppress httpx/httpcore logs from Dropbox SDK
        "httpx": {
            "handlers": ["file"],
            "level": "WARNING",
            "propagate": False,
        },
        "httpcore": {
            "handlers": ["file"],
            "level": "WARNING",
            "propagate": False,
        },
        # "django.request": {
        #     "handlers": ["mail_admins"],
        #     "level": "ERROR",
        #     "propagate": False,
        # },
    },
}

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASS"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
        # Connection pooling - keep connections alive for 600 seconds
        "CONN_MAX_AGE": None,
        # Connection pool size per worker
        "CONN_HEALTH_CHECKS": True,
    }
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.memcached.PyMemcacheCache",
        "LOCATION": os.getenv("MEMCACHED_HOST", "memcached") + ":11211",
        "TIMEOUT": 300,
    },
    "select2": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "TIMEOUT": 300,
    },
}

SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"
# When the cookie expires the user will be required to log in again (after 20 minutes of inactivity)
SESSION_COOKIE_AGE = 60 * 20  # 20 minutes
SESSION_SAVE_EVERY_REQUEST = False  # Only save session if modified (better performance)

# OpenRouter / OpenAI API Configuration
# Timeout settings for LLM API calls (vision models can take 60-120 seconds)
OPENROUTER_TIMEOUT = float(os.getenv("OPENROUTER_TIMEOUT", "120.0"))  # seconds
OPENAI_TIMEOUT = float(os.getenv("OPENAI_TIMEOUT", "120.0"))  # seconds
