# Generated by Django 5.2.4 on 2025-11-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_applications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="docapplication",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
