# Generated by Django 5.2.4 on 2025-11-03 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer_applications", "0002_docapplication_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="docapplication",
            name="application_type",
        ),
    ]
