# Generated by Django 6.0.2 on 2026-02-24 03:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_applications', '0011_alter_workflownotification_status'),
        ('products', '0005_product_retail_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategorizationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('total_files', models.PositiveIntegerField(default=0)),
                ('processed_files', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('request_params', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('traceback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_categorization_jobs', to=settings.AUTH_USER_MODEL)),
                ('doc_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorization_jobs', to='customer_applications.docapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCategorizationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_index', models.PositiveIntegerField(default=0)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('categorized', 'Categorized'), ('error', 'Error')], default='queued', max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('traceback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorization_items', to='customer_applications.document')),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorization_items', to='products.documenttype')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='customer_applications.documentcategorizationjob')),
            ],
            options={
                'ordering': ['sort_index', 'created_at'],
            },
        ),
    ]
