# Generated by Django 6.0.2 on 2026-02-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_applications', '0013_documentcategorizationitem_validation_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ai_validation_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='ai_validation_status',
            field=models.CharField(blank=True, choices=[('', 'Not requested'), ('pending', 'Pending'), ('validating', 'Validating'), ('valid', 'Valid'), ('invalid', 'Invalid'), ('error', 'Error')], default='', max_length=20),
        ),
    ]
