# Generated by Django 6.0.2 on 2026-03-02

import customer_applications.models.document
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_applications", "0015_document_ai_validation_field_rename"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="thumbnail",
            field=models.FileField(blank=True, upload_to=customer_applications.models.document.get_thumbnail_upload_to),
        ),
        migrations.AddField(
            model_name="document",
            name="thumbnail_link",
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
