# Generated by Django 5.2.4 on 2025-11-04 02:21

import core.utils.form_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="customer",
            unique_together={("first_name", "last_name")},
        ),
        migrations.AlterField(
            model_name="customer",
            name="birthdate",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[core.utils.form_validators.validate_birthdate],
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="telephone",
            field=models.CharField(
                db_index=True,
                default=822123456789,
                max_length=50,
                unique=True,
                validators=[core.utils.form_validators.validate_phone_number],
            ),
            preserve_default=False,
        ),
    ]
