# Generated by Django 5.2.4 on 2025-12-26 07:43

import core.utils.form_validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0010_alter_customer_options_customer_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                validators=[core.utils.form_validators.validate_email],
            ),
        ),
    ]
