"""
core.services.invoice_service
=============================
Service layer for creating and updating invoices, reconciling payments, and
synchronising linked customer application statuses.

InvoiceApplicationPayload
--------------------------
Immutable dataclass representing one line of an invoice::

    InvoiceApplicationPayload(
        product_id=42,
        customer_application_id=7,   # may be None for product-only lines
        amount=Decimal("500000"),
        invoice_application_id=None, # set when updating an existing line
    )

invoice_no uniqueness retry logic
----------------------------------
``create_invoice()`` may retry the entire insert up to a configured number of
times when the database raises an ``IntegrityError`` caused by a duplicate
``invoice_no`` (detected by ``_is_invoice_no_unique_conflict()``).  This is
necessary because invoice numbers are auto-generated by a sequence and
concurrent transactions can race.  The retry uses exponential-back-off with
jitter.

public functions
-----------------
- ``create_invoice()`` — create an invoice with application lines in one
  ``transaction.atomic()`` block; retries on ``invoice_no`` collisions.
- ``update_invoice_applications()`` — reconcile the application lines on an
  existing draft invoice; validates product/application constraints.
- ``sync_paid_invoice_applications()`` — mark linked ``DocApplication`` rows
  as ``STATUS_COMPLETED`` when an invoice transitions to ``PAID``.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from decimal import Decimal
from typing import Iterable

from customer_applications.models import DocApplication
from django.db import IntegrityError, transaction
from django.utils import timezone
from invoices.models.invoice import Invoice, InvoiceApplication
from payments.models import Payment
from products.models import Product
from products.models.product_price_history import ProductPriceHistory
from rest_framework.exceptions import ValidationError


@dataclass(frozen=True)
class InvoiceApplicationPayload:
    """Immutable contract for one invoice line item.

    Either ``product_id`` or ``customer_application_id`` (or both) must be
    supplied.  ``invoice_application_id`` is required when updating an
    existing line; leave as ``None`` for new lines.
    """

    product_id: int | None
    """ID of the ``Product`` for this line."""
    customer_application_id: int | None
    """ID of the linked ``DocApplication``; ``None`` for product-only lines."""
    amount: Decimal
    """Line amount in the invoice currency (IDR)."""
    invoice_application_id: int | None = None
    """Existing ``InvoiceApplication.id`` when updating; ``None`` for new lines."""


def _normalize_id(value):
    """Return ``value.id`` for model instances, otherwise return *value* unchanged."""
    return value.id if hasattr(value, "id") else value


def _extract_constraint_name(exc: Exception) -> str | None:
    cause = getattr(exc, "__cause__", None)
    diag = getattr(cause, "diag", None)
    constraint_name = getattr(diag, "constraint_name", None) if diag else None
    if not constraint_name:
        return None
    return str(constraint_name).strip() or None


def _is_invoice_no_unique_conflict(exc: Exception) -> bool:
    """Return ``True`` if *exc* is an ``IntegrityError`` caused by a duplicate ``invoice_no``.

    Checks the PostgreSQL ``diag.constraint_name`` first (precise), then falls
    back to a substring search on the error message (portable).
    """
    if not isinstance(exc, IntegrityError):
        return False

    constraint_name = (_extract_constraint_name(exc) or "").lower()
    if constraint_name and "invoice_no" in constraint_name:
        return True

    message = str(exc).lower()
    return "invoice_no" in message and ("unique" in message or "duplicate" in message)


def sync_paid_invoice_applications(*, invoice: Invoice, user=None) -> int:
    """Mark linked customer applications as completed when invoice is fully paid.

    Kept as an explicit service-layer side effect so it can be invoked from
    transactional write flows (invoice/payment operations) without embedding
    cross-model mutations in ``Invoice.save()``.
    """
    if not invoice or invoice.status != Invoice.PAID:
        return 0

    updated = 0
    linked_applications = (
        DocApplication.objects.filter(invoice_applications__invoice=invoice)
        .exclude(status=DocApplication.STATUS_COMPLETED)
        .distinct()
    )
    for application in linked_applications:
        application.status = DocApplication.STATUS_COMPLETED
        if user and getattr(user, "is_authenticated", False):
            application.updated_by = user
        application.save(skip_status_calculation=True)
        updated += 1
    return updated


def _build_payloads(raw_items: Iterable[dict]) -> list[InvoiceApplicationPayload]:
    items = list(raw_items)
    app_ids = [
        _normalize_id(item.get("customer_application"))
        for item in items
        if _normalize_id(item.get("customer_application"))
    ]
    app_product_map = {
        app_id: product_id
        for app_id, product_id in DocApplication.objects.filter(id__in=app_ids).values_list("id", "product_id")
    }

    payloads: list[InvoiceApplicationPayload] = []
    for item in items:
        customer_application_id = _normalize_id(item.get("customer_application"))
        product_id = _normalize_id(item.get("product")) or app_product_map.get(customer_application_id)
        payloads.append(
            InvoiceApplicationPayload(
                invoice_application_id=item.get("id"),
                customer_application_id=customer_application_id,
                product_id=product_id,
                amount=Decimal(str(item.get("amount"))),
            )
        )
    return payloads


def _resolve_price_history_id(*, product_id: int, invoice_date: date | None) -> int | None:
    history = ProductPriceHistory.resolve_for_invoice_date(product_id=product_id, invoice_date=invoice_date)
    return history.id if history else None


def _validate_application_ids(payloads: list[InvoiceApplicationPayload]) -> None:
    ids = [payload.customer_application_id for payload in payloads if payload.customer_application_id]
    if len(ids) != len(set(ids)):
        raise ValidationError("Each customer application can only appear once in an invoice.")


def _validate_application_availability(
    *,
    payloads: list[InvoiceApplicationPayload],
    customer_id: int,
    current_invoice: Invoice | None = None,
) -> None:
    if any(payload.product_id is None for payload in payloads):
        raise ValidationError({"invoice_applications": ["Each invoice line must include a product."]})

    product_ids = [payload.product_id for payload in payloads if payload.product_id]
    existing_products = Product.objects.filter(id__in=product_ids)
    existing_product_map = {product.id: product for product in existing_products}
    missing_products = sorted({product_id for product_id in product_ids if product_id not in existing_product_map})
    if missing_products:
        raise ValidationError(
            {"invoice_applications": [f"Unknown product id(s): {', '.join(map(str, missing_products))}."]}
        )

    deprecated_products = [product for product in existing_product_map.values() if product.deprecated]
    if deprecated_products:
        raise ValidationError({"invoice_applications": ["Cannot create/update invoice with deprecated products."]})

    application_ids = [payload.customer_application_id for payload in payloads if payload.customer_application_id]
    if not application_ids:
        return

    existing = InvoiceApplication.objects.filter(customer_application_id__in=application_ids)
    if current_invoice:
        existing = existing.exclude(invoice=current_invoice)
    if existing.exists():
        raise ValidationError({"invoice_applications": ["One or more customer applications are already invoiced."]})

    applications = DocApplication.objects.filter(id__in=application_ids).select_related("product", "customer")
    app_map = {application.id: application for application in applications}
    missing_apps = sorted({app_id for app_id in application_ids if app_id not in app_map})
    if missing_apps:
        raise ValidationError(
            {"invoice_applications": [f"Unknown customer application id(s): {', '.join(map(str, missing_apps))}."]}
        )

    for payload in payloads:
        if not payload.customer_application_id:
            continue
        application = app_map[payload.customer_application_id]
        if application.customer_id != customer_id:
            raise ValidationError(
                {"invoice_applications": ["Customer application customer must match invoice customer."]}
            )
        if payload.product_id and application.product_id != payload.product_id:
            raise ValidationError(
                {"invoice_applications": ["Customer application product must match the invoice line product."]}
            )

    deprecated_product_apps = applications.filter(
        product__deprecated=True,
    )
    if deprecated_product_apps.exists():
        raise ValidationError(
            {"invoice_applications": ["Cannot create/update invoice with applications linked to deprecated products."]}
        )

    non_workflow_product_apps = applications.filter(product__uses_customer_app_workflow=False)
    if non_workflow_product_apps.exists():
        raise ValidationError(
            {
                "invoice_applications": [
                    "Customer applications linked to invoice-only products are not billable here. "
                    "Use a product-only invoice line instead."
                ]
            }
        )


def create_invoice(*, data: dict, user) -> Invoice:
    payloads = _build_payloads(data.pop("invoice_applications", []))
    _validate_application_ids(payloads)

    customer = data.get("customer")
    customer_id = customer.id if hasattr(customer, "id") else customer
    if not customer_id:
        raise ValidationError({"customer": ["Customer is required."]})

    _validate_application_availability(payloads=payloads, customer_id=customer_id)

    invoice_date = data.get("invoice_date")
    if isinstance(invoice_date, str):
        try:
            invoice_date = timezone.datetime.fromisoformat(invoice_date).date()
        except Exception:
            invoice_date = None
    year = invoice_date.year if invoice_date else timezone.now().year

    # Always assign the next available invoice number for the year
    data["invoice_no"] = Invoice.get_next_invoice_no_for_year(year)

    # Attempt creation; handle possible race conditions on invoice_no uniqueness by retrying
    attempts = 0
    max_attempts = 3
    while True:
        try:
            with transaction.atomic():
                invoice = Invoice.objects.create(created_by=user, **data)
                _sync_invoice_applications(invoice=invoice, payloads=payloads, user=user)
                invoice.save()
                sync_paid_invoice_applications(invoice=invoice, user=user)
                return invoice
        except Exception as exc:
            # Handle duplicate invoice_no integrity errors specifically.
            if _is_invoice_no_unique_conflict(exc):
                attempts += 1
                if attempts >= max_attempts:
                    raise ValidationError({"invoice_no": ["Invoice number already exists."]})

                # Remove provided invoice_no (if any) so Invoice.save() will generate next available
                data.pop("invoice_no", None)

                # If invoice_date present, compute next invoice number for that year and set it explicitly
                try:
                    invoice_date = data.get("invoice_date")
                    if isinstance(invoice_date, str):
                        invoice_date = timezone.datetime.fromisoformat(invoice_date).date()
                    year = invoice_date.year if invoice_date else timezone.now().year
                except Exception:
                    year = timezone.now().year

                data["invoice_no"] = Invoice.get_next_invoice_no_for_year(year)
                # Try again
                continue
            # re-raise other exceptions
            raise


def update_invoice(*, invoice: Invoice, data: dict, user) -> Invoice:
    payloads = _build_payloads(data.pop("invoice_applications", []))
    _validate_application_ids(payloads)
    _validate_application_availability(payloads=payloads, customer_id=invoice.customer_id, current_invoice=invoice)

    if data.get("customer") and data["customer"].id != invoice.customer_id:
        raise ValidationError("Customer cannot be changed for an existing invoice.")

    with transaction.atomic():
        for attr, value in data.items():
            setattr(invoice, attr, value)
        invoice.updated_by = user
        invoice.save()

        _sync_invoice_applications(invoice=invoice, payloads=payloads, user=user)
        invoice.save()
        sync_paid_invoice_applications(invoice=invoice, user=user)
        return invoice


def _sync_invoice_applications(*, invoice: Invoice, payloads: list[InvoiceApplicationPayload], user) -> None:
    existing = {item.id: item for item in invoice.invoice_applications.all()}
    seen_ids: set[int] = set()

    for payload in payloads:
        history_id = _resolve_price_history_id(product_id=payload.product_id, invoice_date=invoice.invoice_date)
        if payload.invoice_application_id and payload.invoice_application_id in existing:
            invoice_app = existing[payload.invoice_application_id]
            invoice_app.customer_application_id = payload.customer_application_id
            invoice_app.product_id = payload.product_id
            invoice_app.amount = payload.amount
            invoice_app.price_history_id = history_id
            invoice_app.save()
            seen_ids.add(invoice_app.id)
        else:
            invoice_app = InvoiceApplication.objects.create(
                invoice=invoice,
                product_id=payload.product_id,
                customer_application_id=payload.customer_application_id,
                amount=payload.amount,
                price_history_id=history_id,
            )
            seen_ids.add(invoice_app.id)

    to_delete = [item_id for item_id in existing.keys() if item_id not in seen_ids]
    if to_delete:
        InvoiceApplication.objects.filter(id__in=to_delete, invoice=invoice).delete()


def mark_invoice_as_paid(*, invoice: Invoice, payment_type: str, payment_date: date | None, user) -> list[Payment]:
    payment_date = payment_date or timezone.now().date()
    created: list[Payment] = []

    with transaction.atomic():
        # Prefetch existing payments once to avoid per-line aggregate queries when
        # evaluating due_amount for each invoice application.
        invoice_applications = list(invoice.invoice_applications.prefetch_related("payments").all())
        unpaid_apps = [app for app in invoice_applications if app.due_amount > 0]
        if not unpaid_apps:
            return created

        for invoice_app in unpaid_apps:
            payment = create_payment(
                invoice_application=invoice_app,
                amount=Decimal(str(invoice_app.due_amount)),
                payment_type=payment_type,
                payment_date=payment_date,
                user=user,
            )
            created.append(payment)
        invoice.refresh_from_db(fields=["status"])
        sync_paid_invoice_applications(invoice=invoice, user=user)
    return created


def validate_payment_amount(invoice_application: InvoiceApplication, amount: Decimal, payment: Payment | None = None):
    available = Decimal(str(invoice_application.due_amount))
    if payment:
        available += Decimal(str(payment.amount))

    if amount > available:
        raise ValidationError("The payment amount exceeds the due amount.")


def create_payment(
    *,
    invoice_application: InvoiceApplication,
    amount: Decimal,
    payment_type: str,
    payment_date: date | None,
    user,
    notes: str | None = None,
) -> Payment:
    validate_payment_amount(invoice_application, amount)
    payment_date = payment_date or timezone.now().date()

    return Payment.objects.create(
        invoice_application=invoice_application,
        from_customer=invoice_application.invoice.customer,
        payment_date=payment_date,
        payment_type=payment_type,
        amount=amount,
        notes=notes or "",
        created_by=user,
    )


def update_payment(
    *, payment: Payment, amount: Decimal, payment_type: str, payment_date: date | None, user, notes=None
):
    validate_payment_amount(payment.invoice_application, amount, payment)
    payment.amount = amount
    payment.payment_type = payment_type
    payment.payment_date = payment_date or payment.payment_date
    payment.notes = notes or payment.notes
    payment.updated_by = user
    payment.save()
    return payment
