export * from './api-token-auth.service';
import { ApiTokenAuthService } from './api-token-auth.service';
export * from './compute.service';
import { ComputeService } from './compute.service';
export * from './country-codes.service';
import { CountryCodesService } from './country-codes.service';
export * from './cron.service';
import { CronService } from './cron.service';
export * from './customer-applications.service';
import { CustomerApplicationsService } from './customer-applications.service';
export * from './customers.service';
import { CustomersService } from './customers.service';
export * from './dashboard-stats.service';
import { DashboardStatsService } from './dashboard-stats.service';
export * from './document-ocr.service';
import { DocumentOcrService } from './document-ocr.service';
export * from './document-types.service';
import { DocumentTypesService } from './document-types.service';
export * from './documents.service';
import { DocumentsService } from './documents.service';
export * from './invoices.service';
import { InvoicesService } from './invoices.service';
export * from './ocr.service';
import { OcrService } from './ocr.service';
export * from './products.service';
import { ProductsService } from './products.service';
export const APIS = [ApiTokenAuthService, ComputeService, CountryCodesService, CronService, CustomerApplicationsService, CustomersService, DashboardStatsService, DocumentOcrService, DocumentTypesService, DocumentsService, InvoicesService, OcrService, ProductsService];
