/**
 * BusinessSuite API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';

import { CountryCode } from '../model/models';

import { Configuration } from '../configuration';

export interface CountryCodesListRequestParams {
  ordering?: string;
  search?: string;
}

export interface CountryCodesRetrieveRequestParams {
  alpha3Code: string;
}

export interface CountryCodesServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   *
   *
   * @endpoint get /api/country-codes/
   * @param requestParameters
   */
  countryCodesList(
    requestParameters: CountryCodesListRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<Array<CountryCode>>;

  /**
   *
   *
   * @endpoint get /api/country-codes/{alpha3Code}/
   * @param requestParameters
   */
  countryCodesRetrieve(
    requestParameters: CountryCodesRetrieveRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<CountryCode>;
}
