/**
 * BusinessSuite API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import {
  HttpClient,
  HttpHeaders,
  HttpParams,
  HttpResponse,
  HttpEvent,
  HttpContext,
} from '@angular/common/http';
import { Observable } from 'rxjs';
import { OpenApiHttpParams, QueryParamStyle } from '../query.params';

// @ts-ignore
import { CategorizationApplyRequest } from '../model/categorization-apply-request';
// @ts-ignore
import { DocumentCategorizationApplyResponse } from '../model/document-categorization-apply-response';
// @ts-ignore
import { DocumentCategorizationJob } from '../model/document-categorization-job';
// @ts-ignore
import { DocumentCategorizationUploadFilesResponse } from '../model/document-categorization-upload-files-response';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';
import { BaseService } from '../api.base.service';
import {
  DocumentCategorizationServiceInterface,
  DocumentCategorizationApplyCreateRequestParams,
  DocumentCategorizationStatusRetrieveRequestParams,
  DocumentCategorizationUploadCreateRequestParams,
} from './document-categorization.serviceInterface';

@Injectable({
  providedIn: 'root',
})
export class DocumentCategorizationService
  extends BaseService
  implements DocumentCategorizationServiceInterface
{
  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string | string[],
    @Optional() configuration?: Configuration,
  ) {
    super(basePath, configuration);
  }

  /**
   * Apply confirmed categorization results: attach files to Document rows.  After applying the requested mappings, **all** transient files for this job are deleted from storage (&#x60;&#x60;tmp/categorization/{job_id}/&#x60;&#x60;).  This includes unapplied files (e.g. \&quot;No Slot\&quot; or errored items) so that only files copied into their final Document location are persisted.
   * @endpoint post /api/document-categorization/{jobId}/apply/
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public documentCategorizationApplyCreate(
    requestParameters: DocumentCategorizationApplyCreateRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<DocumentCategorizationApplyResponse>;
  public documentCategorizationApplyCreate(
    requestParameters: DocumentCategorizationApplyCreateRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<HttpResponse<DocumentCategorizationApplyResponse>>;
  public documentCategorizationApplyCreate(
    requestParameters: DocumentCategorizationApplyCreateRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<HttpEvent<DocumentCategorizationApplyResponse>>;
  public documentCategorizationApplyCreate(
    requestParameters: DocumentCategorizationApplyCreateRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<any> {
    const jobId = requestParameters?.jobId;
    if (jobId === null || jobId === undefined) {
      throw new Error(
        'Required parameter jobId was null or undefined when calling documentCategorizationApplyCreate.',
      );
    }
    const categorizationApplyRequest = requestParameters?.categorizationApplyRequest;
    if (categorizationApplyRequest === null || categorizationApplyRequest === undefined) {
      throw new Error(
        'Required parameter categorizationApplyRequest was null or undefined when calling documentCategorizationApplyCreate.',
      );
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (cookieAuth) required

    // authentication (jwtAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'jwtAuth',
      'Authorization',
      localVarHeaders,
      'Bearer ',
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept(['application/json']);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json',
      'application/x-www-form-urlencoded',
      'multipart/form-data',
    ];
    const httpContentTypeSelected: string | undefined =
      this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/document-categorization/${this.configuration.encodeParam({ name: 'jobId', value: jobId, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: 'uuid' })}/apply/`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<DocumentCategorizationApplyResponse>(
      'post',
      `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        body: categorizationApplyRequest,
        responseType: <any>responseType_,
        ...(withCredentials ? { withCredentials } : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
        reportProgress: reportProgress,
      },
    );
  }

  /**
   * Polling fallback for categorization job status.
   * @endpoint get /api/document-categorization/{jobId}/status/
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public documentCategorizationStatusRetrieve(
    requestParameters: DocumentCategorizationStatusRetrieveRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<DocumentCategorizationJob>;
  public documentCategorizationStatusRetrieve(
    requestParameters: DocumentCategorizationStatusRetrieveRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<HttpResponse<DocumentCategorizationJob>>;
  public documentCategorizationStatusRetrieve(
    requestParameters: DocumentCategorizationStatusRetrieveRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<HttpEvent<DocumentCategorizationJob>>;
  public documentCategorizationStatusRetrieve(
    requestParameters: DocumentCategorizationStatusRetrieveRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<any> {
    const jobId = requestParameters?.jobId;
    if (jobId === null || jobId === undefined) {
      throw new Error(
        'Required parameter jobId was null or undefined when calling documentCategorizationStatusRetrieve.',
      );
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (cookieAuth) required

    // authentication (jwtAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'jwtAuth',
      'Authorization',
      localVarHeaders,
      'Bearer ',
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept(['application/json']);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/document-categorization/${this.configuration.encodeParam({ name: 'jobId', value: jobId, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: 'uuid' })}/status/`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<DocumentCategorizationJob>('get', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
      reportProgress: reportProgress,
    });
  }

  /**
   * Upload files into an existing categorization job and dispatch item tasks.
   * @endpoint post /api/document-categorization/{jobId}/upload/
   * @param requestParameters
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public documentCategorizationUploadCreate(
    requestParameters: DocumentCategorizationUploadCreateRequestParams,
    observe?: 'body',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<DocumentCategorizationUploadFilesResponse>;
  public documentCategorizationUploadCreate(
    requestParameters: DocumentCategorizationUploadCreateRequestParams,
    observe?: 'response',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<HttpResponse<DocumentCategorizationUploadFilesResponse>>;
  public documentCategorizationUploadCreate(
    requestParameters: DocumentCategorizationUploadCreateRequestParams,
    observe?: 'events',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<HttpEvent<DocumentCategorizationUploadFilesResponse>>;
  public documentCategorizationUploadCreate(
    requestParameters: DocumentCategorizationUploadCreateRequestParams,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<any> {
    const jobId = requestParameters?.jobId;
    if (jobId === null || jobId === undefined) {
      throw new Error(
        'Required parameter jobId was null or undefined when calling documentCategorizationUploadCreate.',
      );
    }
    const files = requestParameters?.files;
    if (files === null || files === undefined) {
      throw new Error(
        'Required parameter files was null or undefined when calling documentCategorizationUploadCreate.',
      );
    }

    let localVarHeaders = this.defaultHeaders;

    // authentication (cookieAuth) required

    // authentication (jwtAuth) required
    localVarHeaders = this.configuration.addCredentialToHeaders(
      'jwtAuth',
      'Authorization',
      localVarHeaders,
      'Bearer ',
    );

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept(['application/json']);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    // to determine the Content-Type header
    const consumes: string[] = ['multipart/form-data', 'application/x-www-form-urlencoded'];

    const canConsumeForm = this.canConsumeForm(consumes);

    let localVarFormParams: { append(param: string, value: any): any };
    let localVarUseForm = false;
    let localVarConvertFormParamsToString = false;
    // use FormData to transmit files using content-type "multipart/form-data"
    // see https://stackoverflow.com/questions/4007969/application-x-www-form-urlencoded-or-multipart-form-data
    localVarUseForm = canConsumeForm;
    if (localVarUseForm) {
      localVarFormParams = new FormData();
    } else {
      localVarFormParams = new HttpParams({ encoder: this.encoder });
    }

    if (files) {
      if (localVarUseForm) {
        files.forEach((element) => {
          localVarFormParams =
            (localVarFormParams.append('files', <any>element) as any) || localVarFormParams;
        });
      } else {
        localVarFormParams =
          (localVarFormParams.append('files', [...files].join(COLLECTION_FORMATS['csv'])) as any) ||
          localVarFormParams;
      }
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/document-categorization/${this.configuration.encodeParam({ name: 'jobId', value: jobId, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: 'uuid' })}/upload/`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<DocumentCategorizationUploadFilesResponse>(
      'post',
      `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        body: localVarConvertFormParamsToString
          ? localVarFormParams.toString()
          : localVarFormParams,
        responseType: <any>responseType_,
        ...(withCredentials ? { withCredentials } : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
        reportProgress: reportProgress,
      },
    );
  }
}
