/**
 * BusinessSuite API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';

import { DocumentType } from '../model/models';
import { DocumentTypeRequest } from '../model/models';

import { Configuration } from '../configuration';

export interface DocumentTypesCanDeleteRetrieveRequestParams {
  id: number;
}

export interface DocumentTypesCreateRequestParams {
  documentTypeRequest: DocumentTypeRequest;
}

export interface DocumentTypesDeprecationImpactRetrieveRequestParams {
  id: number;
}

export interface DocumentTypesDestroyRequestParams {
  id: number;
}

export interface DocumentTypesListRequestParams {
  deprecated?: boolean;
  hideDeprecated?: boolean;
  ordering?: string;
  search?: string;
  usesCustomerAppWorkflow?: boolean;
}

export interface DocumentTypesPartialUpdateRequestParams {
  id: number;
  documentTypeRequest: DocumentTypeRequest;
}

export interface DocumentTypesRetrieveRequestParams {
  id: number;
}

export interface DocumentTypesUpdateRequestParams {
  id: number;
  documentTypeRequest: DocumentTypeRequest;
}

export interface DocumentTypesServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   * Check if a document type can be deleted
   * Check if document type can be safely deleted.
   * @endpoint get /api/document-types/{id}/can-delete/
   * @param requestParameters
   */
  documentTypesCanDeleteRetrieve(
    requestParameters: DocumentTypesCanDeleteRetrieveRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<{ [key: string]: any }>;

  /**
   *
   *
   * @endpoint post /api/document-types/
   * @param requestParameters
   */
  documentTypesCreate(
    requestParameters: DocumentTypesCreateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<DocumentType>;

  /**
   *
   *
   * @endpoint get /api/document-types/{id}/deprecation-impact/
   * @param requestParameters
   */
  documentTypesDeprecationImpactRetrieve(
    requestParameters: DocumentTypesDeprecationImpactRetrieveRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<DocumentType>;

  /**
   *
   *
   * @endpoint delete /api/document-types/{id}/
   * @param requestParameters
   */
  documentTypesDestroy(
    requestParameters: DocumentTypesDestroyRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<{}>;

  /**
   *
   *
   * @endpoint get /api/document-types/
   * @param requestParameters
   */
  documentTypesList(
    requestParameters: DocumentTypesListRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<Array<DocumentType>>;

  /**
   *
   *
   * @endpoint patch /api/document-types/{id}/
   * @param requestParameters
   */
  documentTypesPartialUpdate(
    requestParameters: DocumentTypesPartialUpdateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<DocumentType>;

  /**
   *
   *
   * @endpoint get /api/document-types/{id}/
   * @param requestParameters
   */
  documentTypesRetrieve(
    requestParameters: DocumentTypesRetrieveRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<DocumentType>;

  /**
   *
   *
   * @endpoint put /api/document-types/{id}/
   * @param requestParameters
   */
  documentTypesUpdate(
    requestParameters: DocumentTypesUpdateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<DocumentType>;
}
