/**
 * BusinessSuite API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';

import { Configuration } from '../configuration';

export interface DocumentOcrStatusRetrieveRequestParams {
  jobId: string;
}

export interface DocumentOcrStreamRetrieveRequestParams {
  jobId: string;
}

export interface DocumentOcrServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   *
   *
   * @endpoint post /api/document-ocr/check/
   */
  documentOcrCheckCreate(extraHttpRequestParams?: any): Observable<{}>;

  /**
   *
   *
   * @endpoint get /api/document-ocr/status/{jobId}/
   * @param requestParameters
   */
  documentOcrStatusRetrieve(
    requestParameters: DocumentOcrStatusRetrieveRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<{}>;

  /**
   *
   *
   * @endpoint get /api/document-ocr/stream/{jobId}/
   * @param requestParameters
   */
  documentOcrStreamRetrieve(
    requestParameters: DocumentOcrStreamRetrieveRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<{}>;
}
