/**
 * BusinessSuite API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';

import { Holiday } from '../model/models';
import { HolidayRequest } from '../model/models';

import { Configuration } from '../configuration';

export interface HolidaysCreateRequestParams {
  holidayRequest: HolidayRequest;
}

export interface HolidaysDestroyRequestParams {
  id: number;
}

export interface HolidaysListRequestParams {
  ordering?: string;
  search?: string;
}

export interface HolidaysPartialUpdateRequestParams {
  id: number;
  holidayRequest: HolidayRequest;
}

export interface HolidaysRetrieveRequestParams {
  id: number;
}

export interface HolidaysUpdateRequestParams {
  id: number;
  holidayRequest: HolidayRequest;
}

export interface HolidaysServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   *
   *
   * @endpoint post /api/holidays/
   * @param requestParameters
   */
  holidaysCreate(
    requestParameters: HolidaysCreateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<Holiday>;

  /**
   *
   *
   * @endpoint delete /api/holidays/{id}/
   * @param requestParameters
   */
  holidaysDestroy(
    requestParameters: HolidaysDestroyRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<{}>;

  /**
   *
   *
   * @endpoint get /api/holidays/
   * @param requestParameters
   */
  holidaysList(
    requestParameters: HolidaysListRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<Array<Holiday>>;

  /**
   *
   *
   * @endpoint patch /api/holidays/{id}/
   * @param requestParameters
   */
  holidaysPartialUpdate(
    requestParameters: HolidaysPartialUpdateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<Holiday>;

  /**
   *
   *
   * @endpoint get /api/holidays/{id}/
   * @param requestParameters
   */
  holidaysRetrieve(
    requestParameters: HolidaysRetrieveRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<Holiday>;

  /**
   *
   *
   * @endpoint put /api/holidays/{id}/
   * @param requestParameters
   */
  holidaysUpdate(
    requestParameters: HolidaysUpdateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<Holiday>;
}
