/**
 * BusinessSuite API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';

import { UserSettings } from '../model/models';
import { UserSettingsRequest } from '../model/models';

import { Configuration } from '../configuration';

export interface UserSettingsMePartialUpdateRequestParams {
  userSettingsRequest?: UserSettingsRequest;
}

export interface UserSettingsServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   *
   * Retrieve or partially update current user\&#39;s settings.  Supports GET and PATCH on the same URL &#x60;/me/&#x60;.
   * @endpoint patch /api/user-settings/me/
   * @param requestParameters
   */
  userSettingsMePartialUpdate(
    requestParameters: UserSettingsMePartialUpdateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<UserSettings>;

  /**
   *
   * Retrieve or partially update current user\&#39;s settings.  Supports GET and PATCH on the same URL &#x60;/me/&#x60;.
   * @endpoint get /api/user-settings/me/
   */
  userSettingsMeRetrieve(extraHttpRequestParams?: any): Observable<UserSettings>;
}
