/**
 * BusinessSuite API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdminPushNotificationSend { 
    title?: string;
    body?: string;
    data?: { [key: string]: any; };
    link?: string;
    userId: number;
}

