/**
 * BusinessSuite API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AiModelArchitecture } from './ai-model-architecture';
import { AiModelPricing } from './ai-model-pricing';
import { AiModelCapabilities } from './ai-model-capabilities';

export interface AiModel {
  readonly id: number;
  /**
   * * `openrouter` - OpenRouter * `openai` - OpenAI * `groq` - Groq
   */
  provider: AiModel.ProviderEnum;
  modelId: string;
  name: string;
  description?: string;
  vision?: boolean;
  fileUpload?: boolean;
  reasoning?: boolean;
  contextLength?: number | null;
  maxCompletionTokens?: number | null;
  modality?: string;
  architectureModality?: string;
  architectureTokenizer?: string;
  instructType?: string;
  promptPricePerToken?: string | null;
  completionPricePerToken?: string | null;
  imagePrice?: string | null;
  requestPrice?: string | null;
  topProviderId?: string;
  providerName?: string;
  supportedParameters?: any | null;
  perRequestLimits?: any | null;
  source?: string;
  rawMetadata?: any | null;
  readonly capabilities: AiModelCapabilities;
  readonly pricing: AiModelPricing;
  readonly architecture: AiModelArchitecture;
  readonly createdAt: string;
  readonly updatedAt: string;
}
export namespace AiModel {
  export const ProviderEnum = {
    Openrouter: 'openrouter',
    Openai: 'openai',
    Groq: 'groq',
  } as const;
  export type ProviderEnum = (typeof ProviderEnum)[keyof typeof ProviderEnum];
}
