/**
 * BusinessSuite API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CalendarReminderRequest {
  user: number;
  calendarEvent?: string | null;
  reminderDate: string;
  reminderTime: string;
  timezone?: string;
  content: string;
}
