/**
 * BusinessSuite API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CountryCode { 
    country: string;
    countryIdn?: string | null;
    alpha2Code: string;
    alpha3Code: string;
    numericCode: string;
}

