/**
 * BusinessSuite API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Serializer for Customer model.  Note: This serializer exposes all model fields. Keep `fields = \'__all__\'` to avoid missing fields from the model.
 */
export interface Customer { 
    readonly id: number;
    readonly createdAt: string;
    readonly updatedAt: string;
    /**
     * * `` - --------- * `Mr` - Mr * `Mrs` - Mrs * `Ms` - Ms * `Miss` - Miss * `Dr` - Dr * `Prof` - Prof
     */
    title?: Customer.TitleEnum | null;
    /**
     * * `person` - Person * `company` - Company
     */
    customerType?: Customer.CustomerTypeEnum;
    firstName?: string | null;
    lastName?: string | null;
    companyName?: string | null;
    email?: string | null;
    telephone?: string | null;
    whatsapp?: string | null;
    telegram?: string | null;
    facebook?: string | null;
    instagram?: string | null;
    twitter?: string | null;
    npwp?: string | null;
    nationality?: string | null;
    birthdate?: string | null;
    birthPlace?: string | null;
    passportNumber?: string | null;
    passportIssueDate?: string | null;
    passportExpirationDate?: string | null;
    passportFile?: string | null;
    passportMetadata?: any | null;
    readonly passportExpired: boolean;
    readonly passportExpiringSoon: boolean;
    /**
     * * `` - --------- * `M` - Male * `F` - Female
     */
    gender?: Customer.GenderEnum | null;
    readonly genderDisplay: string;
    readonly nationalityName: string;
    readonly nationalityCode: string;
    addressBali?: string | null;
    addressAbroad?: string | null;
    notifyDocumentsExpiration?: boolean;
    /**
     * * `` - --------- * `Email` - Email * `SMS` - SMS * `WhatsApp` - WhatsApp * `Telegram` - Telegram * `Telephone` - Telephone
     */
    notifyBy?: Customer.NotifyByEnum | null;
    active?: boolean;
    readonly fullName: string;
    readonly fullNameWithCompany: string;
}
export namespace Customer {
    export const TitleEnum = {
        Empty: '',
        Mr: 'Mr',
        Mrs: 'Mrs',
        Ms: 'Ms',
        Miss: 'Miss',
        Dr: 'Dr',
        Prof: 'Prof'
    } as const;
    export type TitleEnum = typeof TitleEnum[keyof typeof TitleEnum];
    export const CustomerTypeEnum = {
        Person: 'person',
        Company: 'company'
    } as const;
    export type CustomerTypeEnum = typeof CustomerTypeEnum[keyof typeof CustomerTypeEnum];
    export const GenderEnum = {
        Empty: '',
        M: 'M',
        F: 'F'
    } as const;
    export type GenderEnum = typeof GenderEnum[keyof typeof GenderEnum];
    export const NotifyByEnum = {
        Empty: '',
        Email: 'Email',
        Sms: 'SMS',
        WhatsApp: 'WhatsApp',
        Telegram: 'Telegram',
        Telephone: 'Telephone'
    } as const;
    export type NotifyByEnum = typeof NotifyByEnum[keyof typeof NotifyByEnum];
}


