/**
 * BusinessSuite API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface DocApplicationCreateUpdate {
  readonly id: number;
  customer: number;
  product: number;
  docDate: string;
  dueDate?: string | null;
  notes?: string | null;
  addDeadlinesToCalendar?: boolean;
  notifyCustomer?: boolean;
  notifyCustomerChannel?: 'email' | 'whatsapp' | null;
  documentTypes?: Array<{ [key: string]: any }>;
}
