/**
 * BusinessSuite API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StatusEnum } from './status-enum';
import { DocWorkflow } from './doc-workflow';
import { Customer } from './customer';
import { Product } from './product';


export interface DocApplicationDetail { 
    readonly id: number;
    readonly customer: Customer;
    readonly product: Product;
    readonly docDate: string;
    readonly dueDate: string | null;
    readonly status: StatusEnum;
    readonly notes: string | null;
    readonly createdAt: string;
    readonly updatedAt: string;
    readonly createdBy: number;
    readonly updatedBy: number | null;
    readonly documents: string;
    readonly workflows: Array<DocWorkflow>;
    readonly strField: string;
}
export namespace DocApplicationDetail {
}


