/**
 * BusinessSuite API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Customer } from './customer';
import { Product } from './product';


export interface DocApplicationInvoice { 
    readonly id: number;
    readonly customer: Customer;
    readonly product: Product;
    readonly docDate: string;
    readonly dueDate: string | null;
    readonly addDeadlinesToCalendar: boolean;
    /**
     * * `pending` - Pending * `processing` - Processing * `completed` - Completed * `rejected` - Rejected
     */
    readonly status: DocApplicationInvoice.StatusEnum;
    readonly notes: string | null;
    readonly strField: string;
}
export namespace DocApplicationInvoice {
    export const StatusEnum = {
        Pending: 'pending',
        Processing: 'processing',
        Completed: 'completed',
        Rejected: 'rejected'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


