/**
 * BusinessSuite API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StatusEnum } from './status-enum';


export interface DocApplicationSerializerWithRelations { 
    readonly id: number;
    customer: number;
    product: number;
    docDate: string;
    dueDate?: string | null;
    status?: StatusEnum;
    notes?: string | null;
    readonly createdAt: string;
    readonly updatedAt: string;
    createdBy: number;
    updatedBy?: number | null;
    /**
     * Check if the application has an invoice.
     */
    readonly hasInvoice: boolean;
    /**
     * Get the invoice ID if it exists.
     */
    readonly invoiceId: number | null;
    /**
     * Check if all required documents are completed.
     */
    readonly readyForInvoice: boolean;
}
export namespace DocApplicationSerializerWithRelations {
}


