/**
 * BusinessSuite API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface GoogleCalendarEventRequest {
  summary: string;
  description?: string;
  startTime: string;
  endTime: string;
  attendees?: any | null;
  notifications?: any | null;
  /**
   * * `1` - 1 * `2` - 2 * `3` - 3 * `4` - 4 * `5` - 5 * `6` - 6 * `7` - 7 * `8` - 8 * `9` - 9 * `10` - 10 * `11` - 11
   */
  colorId?: GoogleCalendarEventRequestColorIdEnum;
  done?: boolean;
}
export enum GoogleCalendarEventRequestColorIdEnum {
  _1 = '1',
  _2 = '2',
  _3 = '3',
  _4 = '4',
  _5 = '5',
  _6 = '6',
  _7 = '7',
  _8 = '8',
  _9 = '9',
  _10 = '10',
  _11 = '11',
}
