/**
 * BusinessSuite API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GoogleCalendarEvent { 
    readonly id: string;
    summary: string;
    description?: string;
    startTime: string;
    endTime: string;
    readonly start: any | null;
    readonly end: any | null;
    readonly htmlLink: string;
}

