/**
 * BusinessSuite API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InvoiceListProduct } from './invoice-list-product';
import { InvoiceListCustomerMinimal } from './invoice-list-customer-minimal';

export interface InvoiceListCustomerApplication {
  readonly id: number;
  readonly product: InvoiceListProduct;
  readonly customer: InvoiceListCustomerMinimal;
  notes?: string | null;
}
