/**
 * BusinessSuite API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocApplicationInvoice } from './doc-application-invoice';
import { Product } from './product';


export interface InvoiceApplicationSummary { 
    readonly id: number;
    readonly product: Product;
    readonly customerApplication: DocApplicationInvoice | null;
    amount: string;
    /**
     * * `pending` - Pending * `partial_payment` - Partial Payment * `paid` - Paid * `overdue` - Overdue * `disputed` - Disputed * `cancelled` - Cancelled * `refunded` - Refunded * `write_off` - Write Off
     */
    status?: InvoiceApplicationSummary.StatusEnum;
    readonly paidAmount: string;
    readonly dueAmount: string;
}
export namespace InvoiceApplicationSummary {
    export const StatusEnum = {
        Pending: 'pending',
        PartialPayment: 'partial_payment',
        Paid: 'paid',
        Overdue: 'overdue',
        Disputed: 'disputed',
        Cancelled: 'cancelled',
        Refunded: 'refunded',
        WriteOff: 'write_off'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


