/**
 * BusinessSuite API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InvoiceListCustomerApplication } from './invoice-list-customer-application';
import { InvoiceListProduct } from './invoice-list-product';

export interface InvoiceApplicationListItem {
  readonly id: number;
  sortOrder?: number;
  readonly product: InvoiceListProduct;
  readonly customerApplication: InvoiceListCustomerApplication | null;
  quantity?: number;
  notes?: string | null;
  amount: string;
  /**
   * * `pending` - Pending * `partial_payment` - Partial Payment * `paid` - Paid * `overdue` - Overdue * `disputed` - Disputed * `cancelled` - Cancelled * `refunded` - Refunded * `write_off` - Write Off
   */
  status?: InvoiceApplicationListItemStatusEnum;
  readonly paidAmount: string;
  readonly dueAmount: string;
}
export enum InvoiceApplicationListItemStatusEnum {
  Pending = 'pending',
  PartialPayment = 'partial_payment',
  Paid = 'paid',
  Overdue = 'overdue',
  Disputed = 'disputed',
  Cancelled = 'cancelled',
  Refunded = 'refunded',
  WriteOff = 'write_off',
}
