/**
 * BusinessSuite API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InvoiceFromApplicationPrefillLine } from './invoice-from-application-prefill-line';
import { Customer } from './customer';
import { DocApplicationInvoice } from './doc-application-invoice';
import { InvoiceFromApplicationPrefillLocks } from './invoice-from-application-prefill-locks';

export interface InvoiceFromApplicationPrefillResponse {
  customer: Customer;
  sourceApplication: DocApplicationInvoice;
  invoiceApplication: InvoiceFromApplicationPrefillLine;
  locks: InvoiceFromApplicationPrefillLocks;
}
