/**
 * BusinessSuite API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface InvoiceApplicationWriteRequest {
  id?: number;
  sortOrder?: number;
  product?: number | null;
  customerApplication?: number | null;
  quantity?: number;
  notes?: string | null;
  amount: string;
}
