/**
 * BusinessSuite API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Payment {
  readonly id: number;
  invoiceApplication: number;
  fromCustomer?: number;
  paymentDate?: string;
  /**
   * * `cash` - Cash * `credit_card` - Credit card * `wire_transfer` - Wire transfer * `crypto` - Crypto * `paypal` - PayPal
   */
  paymentType?: PaymentPaymentTypeEnum;
  amount: string;
  notes?: string;
  readonly createdAt: string;
  readonly createdBy: number | null;
}
export enum PaymentPaymentTypeEnum {
  Cash = 'cash',
  CreditCard = 'credit_card',
  WireTransfer = 'wire_transfer',
  Crypto = 'crypto',
  Paypal = 'paypal',
}
