/**
 * BusinessSuite API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaskNestedRequest } from './task-nested-request';

/**
 * Generic mixin to dynamically redact fields from the serializer if the requesting user lacks read/write access based on RBAC rules.
 */
export interface ProductCreateUpdateRequest {
  name: string;
  code: string;
  description?: string;
  immigrationId?: string | null;
  basePrice?: string | null;
  retailPrice?: string;
  currency?: string;
  productCategory?: number | null;
  /**
   * * `visa` - Visa * `other` - Other
   */
  productType?: ProductCreateUpdateRequestProductTypeEnum | null;
  validity?: number | null;
  documentsMinValidity?: number | null;
  applicationWindowDays?: number | null;
  validationPrompt?: string;
  deprecated?: boolean;
  tasks?: Array<TaskNestedRequest>;
  requiredDocumentIds?: Array<number>;
  optionalDocumentIds?: Array<number>;
}
export enum ProductCreateUpdateRequestProductTypeEnum {
  Visa = 'visa',
  Other = 'other',
}
