/**
 * BusinessSuite API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaskNested } from './task-nested';
import { DocumentType } from './document-type';


export interface ProductDetail { 
    readonly id: number;
    name: string;
    code: string;
    description?: string;
    immigrationId?: string | null;
    basePrice?: string | null;
    retailPrice?: string;
    currency?: string;
    readonly productCategory: number;
    readonly productType: string;
    validity?: number | null;
    requiredDocuments?: string;
    optionalDocuments?: string;
    documentsMinValidity?: number | null;
    applicationWindowDays?: number | null;
    validationPrompt?: string;
    deprecated?: boolean;
    usesCustomerAppWorkflow?: boolean;
    readonly tasks: Array<TaskNested>;
    readonly requiredDocumentTypes: Array<DocumentType>;
    readonly optionalDocumentTypes: Array<DocumentType>;
    readonly createdAt: string;
    readonly updatedAt: string;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    readonly createdBy: string;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    readonly updatedBy: string;
}

