/**
 * BusinessSuite API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductTypeEnum } from './product-type-enum';


export interface Product { 
    readonly id: number;
    name: string;
    code: string;
    description?: string;
    immigration_id?: string | null;
    base_price?: string | null;
    product_type?: ProductTypeEnum;
    validity?: number | null;
    required_documents?: string;
    optional_documents?: string;
    documents_min_validity?: number | null;
}
export namespace Product {
}


