/**
 * BusinessSuite API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaskNested } from './task-nested';

/**
 * Generic mixin to dynamically redact fields from the serializer if the requesting user lacks read/write access based on RBAC rules.
 */
export interface ProductCreateUpdate {
  readonly id: number;
  name: string;
  code: string;
  description?: string;
  immigrationId?: string | null;
  basePrice?: string | null;
  retailPrice?: string;
  currency?: string;
  productCategory?: number | null;
  validity?: number | null;
  documentsMinValidity?: number | null;
  applicationWindowDays?: number | null;
  validationPrompt?: string;
  deprecated?: boolean;
  tasks?: Array<TaskNested>;
}
