/**
 * BusinessSuite API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `pending` - Pending * `processing` - Processing * `completed` - Completed * `rejected` - Rejected
 */
export const StatusEnum = {
    Pending: 'pending',
    Processing: 'processing',
    Completed: 'completed',
    Rejected: 'rejected'
} as const;
export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];

