/**
 * BusinessSuite API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserProfile { 
    readonly id: number;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    readonly username: string;
    email?: string;
    firstName?: string;
    lastName?: string;
    readonly fullName: string;
    readonly role: string;
    readonly avatar: string;
    readonly lastLogin: string | null;
    /**
     * Designates that this user has all permissions without explicitly assigning them.
     */
    readonly isSuperuser: boolean;
}

