/**
 * BusinessSuite API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface WorkflowNotificationRequest {
  /**
   * * `pending` - Pending * `sent` - Sent * `delivered` - Delivered * `read` - Read * `failed` - Failed * `cancelled` - Cancelled
   */
  status?: WorkflowNotificationRequest.StatusEnum;
  channel?: string;
  subject: string;
  body: string;
  recipient: string;
  scheduledFor?: string | null;
  notificationType?: string;
  targetDate?: string | null;
  docApplication: number;
  docWorkflow?: number | null;
  createdBy?: number | null;
}
export namespace WorkflowNotificationRequest {
  export const StatusEnum = {
    Pending: 'pending',
    Sent: 'sent',
    Delivered: 'delivered',
    Read: 'read',
    Failed: 'failed',
    Cancelled: 'cancelled',
  } as const;
  export type StatusEnum = (typeof StatusEnum)[keyof typeof StatusEnum];
}
