# Generated by Django 4.2.1 on 2023-05-29 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import customer_applications.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customers", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocApplication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "application_type",
                    models.CharField(choices=[("visa", "Visa"), ("other", "Other")], default="other", max_length=50),
                ),
                ("doc_date", models.DateField()),
                ("price", models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="customers.customer")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.product")),
            ],
            options={
                "ordering": ["application_type"],
            },
        ),
        migrations.CreateModel(
            name="RequiredDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("doc_type", models.CharField(max_length=100)),
                ("doc_number", models.CharField(blank=True, max_length=50)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(blank=True, upload_to=customer_applications.models.RequiredDocument.get_upload_to),
                ),
                ("file_link", models.CharField(blank=True, max_length=1024)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "doc_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="required_documents",
                        to="customer_applications.docapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["doc_type"],
            },
        ),
        migrations.CreateModel(
            name="DocWorkflow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("application_date", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "doc_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to="customer_applications.docapplication",
                    ),
                ),
                ("task", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="products.task")),
            ],
            options={
                "ordering": ["application_date"],
            },
        ),
    ]
