# Generated by Django 4.2.1 on 2023-05-29 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docapplication',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_by_doc_application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='docworkflow',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_by_doc_workflow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requireddocument',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_by_required_document', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='docapplication',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by_doc_application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='docworkflow',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by_doc_workflow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requireddocument',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by_required_document', to=settings.AUTH_USER_MODEL),
        ),
    ]
