# Generated by Django 4.2.2 on 2023-07-13 00:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer_applications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="docapplication",
            name="price",
        ),
    ]
