# Generated by Django 4.2.2 on 2023-07-13 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_customer_active"),
        ("products", "0001_initial"),
        ("customer_applications", "0002_remove_docapplication_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docapplication",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doc_applications",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="docapplication",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doc_applications",
                to="products.product",
            ),
        ),
    ]
