# Generated by Django 4.2.1 on 2023-05-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_applications', '0002_docapplication_updated_by_docworkflow_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requireddocument',
            name='ocr_check',
            field=models.BooleanField(default=False),
        ),
    ]
