# Generated by Django 4.2.1 on 2023-06-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_applications', '0003_requireddocument_ocr_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='requireddocument',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
