# Generated by Django 4.2.1 on 2023-06-06 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_documents_min_validity'),
        ('customer_applications', '0006_alter_docworkflow_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docworkflow',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='products.task'),
        ),
    ]
