# Generated by Django 4.2.2 on 2023-06-08 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_documents_min_validity'),
        ('customer_applications', '0007_alter_docworkflow_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docworkflow',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='docworkflow',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_workflows', to='products.task'),
        ),
    ]
