# Generated by Django 4.2.2 on 2023-06-09 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_applications', '0008_alter_docworkflow_options_alter_docworkflow_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docapplication',
            options={},
        ),
    ]
