# Generated by Django 4.2.2 on 2023-06-09 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_applications', '0009_alter_docapplication_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docapplication',
            options={'ordering': ['-id']},
        ),
    ]
