# Generated by Django 4.2.2 on 2023-06-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_applications', '0010_alter_docapplication_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='docapplication',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
