# Generated by Django 4.2.2 on 2023-06-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_applications', '0012_alter_docapplication_application_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requireddocument',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
