# Generated by Django 4.2.2 on 2023-06-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_applications', '0013_requireddocument_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requireddocument',
            name='completed',
            field=models.BooleanField(),
        ),
    ]
