# Generated by Django 4.2.2 on 2023-06-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_applications', '0014_alter_requireddocument_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requireddocument',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
