# Generated by Django 4.2.2 on 2023-06-15 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_rename_doc_number_regex_documenttype_validation_rule_regex"),
        ("customer_applications", "0015_alter_requireddocument_completed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="requireddocument",
            options={"ordering": ["-expiration_date"]},
        ),
        migrations.AlterField(
            model_name="requireddocument",
            name="doc_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="products.documenttype"
            ),
        ),
        migrations.AlterField(
            model_name="requireddocument",
            name="file",
            field=models.FileField(blank=True, upload_to=""),
        ),
    ]
