# Generated by Django 4.2.2 on 2023-06-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_applications", "0016_alter_requireddocument_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="docapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=50,
            ),
        ),
    ]
