# Generated by Django 4.2.2 on 2023-06-19 00:09

import customer_applications.models.required_document
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer_applications", "0017_docapplication_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="requireddocument",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterField(
            model_name="requireddocument",
            name="created_at",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="requireddocument",
            name="file",
            field=models.FileField(
                blank=True,
                upload_to=customer_applications.models.required_document.RequiredDocument.get_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="requireddocument",
            name="updated_at",
            field=models.DateTimeField(db_index=True),
        ),
    ]
