# Generated by Django 4.2.2 on 2023-06-20 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import customer_applications.models.document


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0013_remove_documenttype_print_template_and_more"),
        ("customer_applications", "0018_alter_requireddocument_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doc_number", models.CharField(blank=True, max_length=50)),
                (
                    "expiration_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        upload_to=customer_applications.models.document.Document.get_upload_to,
                    ),
                ),
                ("file_link", models.CharField(blank=True, max_length=1024)),
                ("ocr_check", models.BooleanField(default=False)),
                ("details", models.TextField(blank=True)),
                ("completed", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(db_index=True)),
                ("updated_at", models.DateTimeField(db_index=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_by_document",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doc_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="customer_applications.docapplication",
                    ),
                ),
                (
                    "doc_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.documenttype",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updated_by_document",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.DeleteModel(
            name="RequiredDocument",
        ),
    ]
