# Generated by Django 4.2.1 on 2023-05-26 09:33

import core.utils.form_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True, validators=[core.utils.form_validators.validateEmail])),
                ('telephone', models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[core.utils.form_validators.validate_phone_number])),
                ('whatsapp', models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[core.utils.form_validators.validate_phone_number])),
                ('telegram', models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[core.utils.form_validators.validate_phone_number])),
                ('title', models.CharField(choices=[('', '---------'), ('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Miss', 'Miss'), ('Dr', 'Dr'), ('Prof', 'Prof')], max_length=50)),
                ('citizenship', models.CharField(max_length=100)),
                ('birthdate', models.DateField(validators=[core.utils.form_validators.validate_birthdate])),
                ('address_bali', models.TextField(blank=True, null=True)),
                ('address_abroad', models.TextField(blank=True, null=True)),
                ('document_type', models.CharField(choices=[('', '---------'), ('Passport', 'Passport'), ('KTP', 'KTP'), ('SIM', 'SIM')], max_length=50)),
                ('document_id', models.CharField(max_length=50, unique=True, validators=[core.utils.form_validators.validate_document_id])),
                ('expiration_date', models.DateField(validators=[core.utils.form_validators.validateExpirationDate])),
                ('notify_expiration', models.BooleanField(default=True)),
                ('notify_by', models.CharField(blank=True, choices=[('', '---------'), ('Email', 'Email'), ('SMS', 'SMS'), ('WhatsApp', 'WhatsApp'), ('Telegram', 'Telegram'), ('Telephone', 'Telephone')], max_length=50, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['full_name'],
                'unique_together': {('full_name', 'birthdate')},
            },
        ),
    ]
