# Generated by Django 4.2.2 on 2023-07-02 04:30

import core.utils.form_validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(db_index=True, max_length=50)),
                ("last_name", models.CharField(db_index=True, max_length=50)),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        validators=[core.utils.form_validators.validate_email],
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        validators=[core.utils.form_validators.validate_phone_number],
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        validators=[core.utils.form_validators.validate_phone_number],
                    ),
                ),
                (
                    "telegram",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        validators=[core.utils.form_validators.validate_phone_number],
                    ),
                ),
                (
                    "facebook",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                (
                    "instagram",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                (
                    "twitter",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("", "---------"),
                            ("Mr", "Mr"),
                            ("Mrs", "Mrs"),
                            ("Ms", "Ms"),
                            ("Miss", "Miss"),
                            ("Dr", "Dr"),
                            ("Prof", "Prof"),
                        ],
                        max_length=50,
                    ),
                ),
                ("nationality", models.CharField(db_index=True, max_length=100)),
                (
                    "birthdate",
                    models.DateField(
                        validators=[core.utils.form_validators.validate_birthdate]
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("", "---------"), ("M", "Male"), ("F", "Female")],
                        max_length=5,
                        null=True,
                    ),
                ),
                ("address_bali", models.TextField(blank=True, null=True)),
                ("address_abroad", models.TextField(blank=True, null=True)),
                ("notify_documents_expiration", models.BooleanField(default=True)),
                (
                    "notify_by",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "---------"),
                            ("Email", "Email"),
                            ("SMS", "SMS"),
                            ("WhatsApp", "WhatsApp"),
                            ("Telegram", "Telegram"),
                            ("Telephone", "Telephone"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("notification_sent", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["first_name", "last_name"],
                "unique_together": {("first_name", "last_name", "birthdate")},
            },
        ),
    ]
