# Generated by Django 4.2.1 on 2023-05-31 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='notify_expiration',
            new_name='notify_documents_expiration',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='document_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='expiration_date',
        ),
    ]
