# Generated by Django 4.2.2 on 2023-07-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
