# Generated by Django 4.2.2 on 2023-06-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_notify_expiration_customer_notify_documents_expiration_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['full_name'], name='full_name_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='email_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['telephone'], name='telephone_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['telegram'], name='telegram_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['whatsapp'], name='whatsapp_idx'),
        ),
    ]
