# Generated by Django 5.2.7 on 2025-11-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_alter_customer_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="company_name",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="customer_type",
            field=models.CharField(
                choices=[("person", "Person"), ("company", "Company")],
                db_index=True,
                default="person",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="npwp",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=30,
                null=True,
                verbose_name="NPWP (Indonesia)",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="first_name",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="last_name",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "---------"),
                    ("Mr", "Mr"),
                    ("Mrs", "Mrs"),
                    ("Ms", "Ms"),
                    ("Miss", "Miss"),
                    ("Dr", "Dr"),
                    ("Prof", "Prof"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
