# Generated by Django 4.2.1 on 2023-05-23 08:30

import core.utils.form_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_address_bali_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birthdate',
            field=models.DateField(validators=[core.utils.form_validators.validate_birthdate]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='document_id',
            field=models.CharField(max_length=50, unique=True, validators=[core.utils.form_validators.validate_document_id]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='document_type',
            field=models.CharField(choices=[('', '---------'), ('Passport', 'Passport'), ('KTP', 'KTP'), ('SIM', 'SIM')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True, validators=[core.utils.form_validators.validateEmail]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='expiration_date',
            field=models.DateField(validators=[core.utils.form_validators.validateExpirationDate]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='notify_by',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Email', 'Email'), ('SMS', 'SMS'), ('WhatsApp', 'WhatsApp'), ('Telegram', 'Telegram'), ('Telephone', 'Telephone')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[core.utils.form_validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='title',
            field=models.CharField(choices=[('', '---------'), ('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Miss', 'Miss'), ('Dr', 'Dr'), ('Prof', 'Prof')], max_length=50),
        ),
    ]
