# Generated by Django 4.2.1 on 2023-05-24 12:59

import core.utils.form_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_birthdate_alter_customer_document_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='telegram',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[core.utils.form_validators.validate_phone_number]),
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[core.utils.form_validators.validate_phone_number]),
        ),
    ]
