# Generated by Django 4.2.2 on 2023-06-10 11:30

import core.utils.form_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_full_name_idx_customer_email_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='full_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='email_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='telephone_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='telegram_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='whatsapp_idx',
        ),
        migrations.AlterField(
            model_name='customer',
            name='citizenship',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=50, null=True, unique=True, validators=[core.utils.form_validators.validateEmail]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telegram',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, validators=[core.utils.form_validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telephone',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, validators=[core.utils.form_validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='whatsapp',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, validators=[core.utils.form_validators.validate_phone_number]),
        ),
    ]
