# Generated by Django 5.2.7 on 2025-11-06 09:32

import core.utils.form_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_customer_company_name_customer_customer_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="telephone",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                unique=True,
                validators=[core.utils.form_validators.validate_phone_number],
            ),
        ),
    ]
