# Generated by Django 5.2.7 on 2025-11-06 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_alter_customer_telephone"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="customer",
            unique_together=set(),
        ),
    ]
