# Generated by Django 4.2.2 on 2023-06-10 11:32

from django.db import migrations, models

import core.utils.form_validators


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0004_remove_customer_full_name_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="citizenship",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                validators=[core.utils.form_validators.validate_email],
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="full_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="customer",
            name="telegram",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                validators=[core.utils.form_validators.validate_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="telephone",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                validators=[core.utils.form_validators.validate_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="whatsapp",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                validators=[core.utils.form_validators.validate_phone_number],
            ),
        ),
    ]
