# Generated by Django 4.2.2 on 2023-06-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0006_alter_customer_citizenship_alter_customer_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="citizenship",
            new_name="nationality",
        ),
        migrations.AddField(
            model_name="customer",
            name="gender",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
