# Generated by Django 5.2.7 on 2025-11-27 10:18

import core.utils.form_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0007_add_birth_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="telegram",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                validators=[core.utils.form_validators.validate_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="telephone",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                validators=[core.utils.form_validators.validate_phone_number],
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="whatsapp",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                validators=[core.utils.form_validators.validate_phone_number],
            ),
        ),
    ]
