# Generated by Django 4.2.2 on 2023-06-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0007_rename_citizenship_customer_nationality_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["last_name", "first_name"]},
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="full_name",
            new_name="first_name",
        ),
        migrations.AlterUniqueTogether(
            name="customer",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="customer",
            name="last_name",
            field=models.CharField(db_index=True, default="XXXXXX", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="customer",
            unique_together={("first_name", "last_name", "birthdate")},
        ),
    ]
