# Generated by Django 5.2.4 on 2025-11-30 02:04

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0008_remove_unique_phone_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="passport_file",
            field=models.FileField(
                blank=True, null=True, upload_to=customers.models.get_passport_upload_to
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="passport_metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
