# Generated by Django 4.2.2 on 2023-06-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0008_alter_customer_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="facebook",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="instagram",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="twitter",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
