# Generated by Django 4.2.2 on 2023-06-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0009_customer_facebook_customer_instagram_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["first_name", "last_name"]},
        ),
        migrations.AlterField(
            model_name="customer",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("", "---------"), ("M", "Male"), ("F", "Female")],
                max_length=5,
                null=True,
            ),
        ),
    ]
