# Generated by Django 4.2.2 on 2023-07-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("credit_card", "Credit card"),
                    ("wire_transfer", "Wire transfer"),
                    ("crypto", "Crypto"),
                    ("paypal", "PayPal"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
    ]
