# Generated by Django 4.2.1 on 2023-05-26 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_telegram_customer_whatsapp'),
        ('docs_workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docapplication',
            name='customer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='waiting_documents', max_length=50),
        ),
    ]
