export * from './apiTokenAuth.service';
import { ApiTokenAuthService } from './apiTokenAuth.service';
export * from './compute.service';
import { ComputeService } from './compute.service';
export * from './cron.service';
import { CronService } from './cron.service';
export * from './customerApplications.service';
import { CustomerApplicationsService } from './customerApplications.service';
export * from './customers.service';
import { CustomersService } from './customers.service';
export * from './documentOcr.service';
import { DocumentOcrService } from './documentOcr.service';
export * from './invoices.service';
import { InvoicesService } from './invoices.service';
export * from './ocr.service';
import { OcrService } from './ocr.service';
export * from './products.service';
import { ProductsService } from './products.service';
export const APIS = [ApiTokenAuthService, ComputeService, CronService, CustomerApplicationsService, CustomersService, DocumentOcrService, InvoicesService, OcrService, ProductsService];
