# Generated by Django 5.2.4 on 2025-11-01 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_invoice_bank_details_invoice_imported_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InvoiceLineItem",
        ),
    ]
