"""Add lookup indexes and related schema improvements for invoice document jobs."""

# Generated by Django 6.0.2 on 2026-03-06 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0007_invoiceapplication_product_refactor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="invoicedocumentjob",
            index=models.Index(fields=["created_by", "status", "-created_at", "-id"], name="inv_doc_guard_lookup_idx"),
        ),
        migrations.AddIndex(
            model_name="invoicedownloadjob",
            index=models.Index(
                fields=["invoice", "format_type", "created_by", "status", "-created_at", "-id"],
                name="inv_dl_guard_lookup_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoiceimportjob",
            index=models.Index(fields=["created_by", "status", "-created_at", "-id"], name="inv_import_guard_idx"),
        ),
    ]
