"""Add the overpaid invoice status to billing state choices."""

# Generated by Django 6.0.3 on 2026-03-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0009_invoiceapplication_price_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("pending_payment", "Pending Payment"),
                    ("partial_payment", "Partial Payment"),
                    ("paid", "Paid"),
                    ("overdue", "Overdue"),
                    ("disputed", "Disputed"),
                    ("cancelled", "Cancelled"),
                    ("partially_refunded", "Partially Refunded"),
                    ("refunded", "Refunded"),
                    ("write_off", "Write Off"),
                    ("overpaid", "Overpaid"),
                ],
                db_index=True,
                default="created",
                max_length=20,
            ),
        ),
    ]
