"""
Django settings for business_suite project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import logging
import os
from datetime import timedelta
from pathlib import Path

from core.utils.dropbox_refresh_token import refresh_dropbox_token
from dotenv import load_dotenv
from peewee import PostgresqlDatabase

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Ensure logs directory exists at the project root (one level up from BASE_DIR)
# This ensures that Grafana Alloy can consistently scrape them from a single location.
ROOT_DIR = BASE_DIR.parent
LOG_DIR = os.path.join(ROOT_DIR, "logs")
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR, exist_ok=True)
LOGS_DIR = LOG_DIR  # Alias for backward compatibility
# enable or disable client-side logging endpoint
CLIENT_LOGS_ENABLED = os.getenv("CLIENT_LOGS_ENABLED") == "True"

# Static and Media paths - defined early as they are used by other settings and services
# Allow overriding via env var so production can point MEDIA_ROOT to a host-mounted path
MEDIA_ROOT = os.getenv("MEDIA_ROOT", os.path.join(BASE_DIR, "files/media/"))
MEDIA_URL = os.getenv("MEDIA_URL", "/uploads/")
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATIC_SOURCE_ROOT = os.path.join(BASE_DIR, "static")

DOCUMENTS_FOLDER = "documents"
APPLICATION_DEFAULT_FILES_FOLDER = "application_default_files"
TMPFILES_FOLDER = "tmpfiles"

# Critical Document Template Settings - must be defined early to avoid circular import issues
DOCX_INVOICE_TEMPLATE_NAME = os.getenv("DOCX_INVOICE_TEMPLATE_NAME", "invoice_template_with_footer.docx")
DOCX_PARTIAL_INVOICE_TEMPLATE_NAME = os.getenv(
    "DOCX_PARTIAL_INVOICE_TEMPLATE_NAME", "partial_invoice_template_with_footer.docx"
)
DOCX_SURAT_PERMOHONAN_PERPANJANGAN_TEMPLATE_NAME = os.getenv(
    "DOCX_SURAT_PERMOHONAN_PERPANJANGAN_TEMPLATE_NAME", "surat_permohonan_perpanjangan.docx"
)

# Document Type Hooks Settings
# Path to the default sponsor passport file (relative to MEDIA_ROOT)
DEFAULT_SPONSOR_PASSPORT_FILE_PATH = os.getenv(
    "DEFAULT_SPONSOR_PASSPORT_FILE_PATH", "default_documents/default_sponsor_document.pdf"
)

# default language for generated documents
DEFAULT_DOCUMENT_LANGUAGE_CODE = os.getenv("DEFAULT_DOCUMENT_LANGUAGE_CODE", "id")

DEFAULT_CUSTOMER_EMAIL = os.getenv("DEFAULT_CUSTOMER_EMAIL", "sample_email@gmail.com")


# MOCK AUTH SETTINGS
def _parse_bool(value, default=False):
    if value is None:
        return default
    if isinstance(value, bool):
        return value
    # Strip common quote characters and whitespace
    s = str(value).strip().strip('"').strip("'").lower()
    return s in {"true", "1", "yes", "y", "on"}


def _parse_list(value, default=None):
    if value is None:
        return default if default is not None else []
    items = [item.strip() for item in str(value).split(",")]
    return [item for item in items if item]


MOCK_AUTH_ENABLED = _parse_bool(os.getenv("MOCK_AUTH_ENABLED", "False"))
MOCK_AUTH_USERNAME = os.getenv("MOCK_AUTH_USERNAME", "mockuser")
MOCK_AUTH_EMAIL = os.getenv("MOCK_AUTH_EMAIL", "mock@example.com")
MOCK_AUTH_IS_SUPERUSER = _parse_bool(os.getenv("MOCK_AUTH_IS_SUPERUSER", "True"))
MOCK_AUTH_IS_STAFF = _parse_bool(os.getenv("MOCK_AUTH_IS_STAFF", "True"))
MOCK_AUTH_GROUPS = _parse_list(os.getenv("MOCK_AUTH_GROUPS", "admin"))
MOCK_AUTH_ROLES = _parse_list(os.getenv("MOCK_AUTH_ROLES", "admin"))

GLOBAL_SETTINGS = {
    "SITE_NAME": os.getenv("SITE_NAME", "Business Suite"),
    "SITE_DESCRIPTION": os.getenv(
        "SITE_DESCRIPTION",
        "Comprehensive ERP for service agencies: CRM, catalog, applications, invoicing, payments, document management.",
    ),
    "DOCUMENT_EXPIRATION_NOTIFICATION_DAYS": 180,
    "LOGO_FILENAME": os.getenv("LOGO_FILENAME", "logo_transparent.png"),
    "LOGO_INVERTED_FILENAME": os.getenv("LOGO_INVERTED_FILENAME", "logo_inverted_transparent.png"),
}

# When True, legacy Django views (non-admin, non-api) are disabled and return 403.
# Can be toggled via env var DISABLE_DJANGO_VIEWS or managed via a waffle flag named "disable_django_views"
DISABLE_DJANGO_VIEWS = _parse_bool(os.getenv("DISABLE_DJANGO_VIEWS", "False"))

# If Django views are disabled, it's safer to redirect logins to the admin
# interface (which is exempt). This prevents users from being redirected to
# the site root ("/") which may be blocked by the DisableDjangoViewsMiddleware.
if DISABLE_DJANGO_VIEWS:
    LOGIN_REDIRECT_URL = "/admin/"

# Invoice Import Settings
INVOICE_IMPORT_MAX_WORKERS = int(os.getenv("INVOICE_IMPORT_MAX_WORKERS", "3"))  # Max parallel imports

# Logging level configuration
DJANGO_LOG_LEVEL = os.getenv("DJANGO_LOG_LEVEL", os.getenv("LOG_LEVEL", "INFO"))
LOGGING_LEVEL = DJANGO_LOG_LEVEL


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
APP_DOMAIN = os.getenv("APP_DOMAIN")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "False") == "True"

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "[::1]",
    os.getenv("APP_DOMAIN", ""),
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "core.apps.CoreConfig",
    "landing",
    "customers",
    "products",
    "invoices.apps.InvoicesConfig",
    "payments",
    "customer_applications",
    "letters",
    "reports",
    "corsheaders",
    "rest_framework",
    "drf_spectacular",
    "rest_framework.authtoken",
    "widget_tweaks",
    "nested_admin",
    "crispy_forms",
    "crispy_bootstrap5",
    "django.contrib.humanize",
    "django_unicorn",
    "debug_toolbar",
    "waffle",
    "dbbackup",
    "storages",
    "admin_tools",
    "django_cleanup.apps.CleanupConfig",
    "django_user_agents",
    "huey.contrib.djhuey",
]

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.middleware.security.SecurityMiddleware",
    # CORS middleware should be as high as possible so CORS headers are applied
    # to all responses (see django-cors-headers docs).
    "corsheaders.middleware.CorsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # to serve static files
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # Waffle must be after AuthenticationMiddleware to access request.user
    "waffle.middleware.WaffleMiddleware",
    # Custom middlewares that might rely on Waffle flags or Auth
    "business_suite.middlewares.disable_django_views.DisableDjangoViewsMiddleware",
    "business_suite.middlewares.AuthLoginRequiredMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # it merge all changes of object per request
    "django_user_agents.middleware.UserAgentMiddleware",
    "core.middleware.performance_logger.PerformanceLoggingMiddleware",
]

ROOT_URLCONF = "business_suite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.request",
                "business_suite.context_processors.site_info",
            ],
        },
    },
]

WSGI_APPLICATION = "business_suite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": os.path.join(BASE_DIR, "files/db.sqlite3"),
#     }
# }
# Use an in-memory SQLite DB when running tests to avoid requiring Postgres.
import sys

TESTING = any("pytest" in arg for arg in sys.argv) or os.getenv("PYTEST_CURRENT_TEST") is not None

if TESTING:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": ":memory:",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME"),
            "USER": os.getenv("DB_USER"),
            "PASSWORD": os.getenv("DB_PASS"),
            "HOST": os.getenv("DB_HOST"),
            "PORT": os.getenv("DB_PORT"),
            # Connection pooling - keep connections alive for 600 seconds
            "CONN_MAX_AGE": 600,
            # Connection pool size per worker
            "CONN_HEALTH_CHECKS": True,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Singapore"

USE_I18N = True

USE_TZ = True

# Google API settings (service account file path, scopes, timezone)
_google_file = os.getenv("GOOGLE_SERVICE_ACCOUNT_FILE", "crm-revisbali-94d3dc9b6077.json").strip('"').strip("'")
if not os.path.isabs(_google_file):
    GOOGLE_SERVICE_ACCOUNT_FILE = os.path.join(ROOT_DIR, _google_file)
else:
    GOOGLE_SERVICE_ACCOUNT_FILE = _google_file

GOOGLE_SCOPES = _parse_list(
    os.getenv(
        "GOOGLE_SCOPES",
        "https://www.googleapis.com/auth/calendar,https://www.googleapis.com/auth/tasks",
    )
)
GOOGLE_TIMEZONE = os.getenv("GOOGLE_TIMEZONE", "Asia/Makassar")
GOOGLE_CALENDAR_ID = os.getenv("GOOGLE_CALENDAR_ID", "primary")
GOOGLE_TASKLIST_ID = os.getenv("GOOGLE_TASKLIST_ID", "@default")

# Configure project locale path for translations (locale is at project root, one level up from BASE_DIR)
LOCALE_PATHS = [os.path.join(BASE_DIR, "..", "locale")]

# Audit configuration: Audits are persisted by `django-auditlog` (DB `LogEntry` objects). Local
# Audit settings (using django-auditlog)
# Runtime toggles controlled by environment variables. Defaults to True when not set.
# Global audit enable/disable at startup. When False, django-auditlog app and middleware are omitted.
AUDIT_ENABLED = _parse_bool(os.getenv("AUDIT_ENABLED", "True"))
# Per-event watch flags (control which events are recorded/forwarded)
AUDIT_WATCH_CRUD_EVENTS = _parse_bool(
    os.getenv("AUDIT_WATCH_CRUD_EVENTS", os.getenv("AUDIT_WATCH_MODEL_EVENTS", "True"))
)
AUDIT_WATCH_AUTH_EVENTS = _parse_bool(os.getenv("AUDIT_WATCH_AUTH_EVENTS", "True"))
AUDIT_WATCH_REQUEST_EVENTS = _parse_bool(os.getenv("AUDIT_WATCH_REQUEST_EVENTS", "True"))
# Avoid logging request events for static/media files when forwarding structured logs. Support comma-separated env var.
AUDIT_URL_SKIP_LIST = _parse_list(os.getenv("AUDIT_URL_SKIP_LIST"), ["/static/", "/media/", "/favicon.ico"])
# Purge retention for forwarded audit logs (not the DB retention of LogEntry)
AUDIT_PURGE_AFTER_DAYS = int(os.getenv("AUDIT_PURGE_AFTER_DAYS", "90"))


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

#
# STEF
#


# by default, all views require login. To allow anonymous access, add the view name to UNAUTHENTICATED_URLS
LOGIN_URL = "/login/"
LOGOUT_URL = "/logout/"
LOGIN_EXEMPT_URLS = (
    r"^login/$",
    r"^logout/$",
    r"^api/.*$",  # match 'api/' and any subpaths
    r"^api-token-auth/$",
)

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login"

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_DOMAIN = APP_DOMAIN
SESSION_COOKIE_DOMAIN = APP_DOMAIN
CSRF_TRUSTED_ORIGINS = [
    f"https://www.admin.{APP_DOMAIN}",
    f"https://admin.{APP_DOMAIN}",
    f"https://www.{APP_DOMAIN}",
    f"https://{APP_DOMAIN}",
    "https://localhost",
    "http://localhost",
    "http://localhost:4200",
]
SESSION_COOKIE_SAMESITE = "Lax"  # Changed from "None" - use Lax for same-site Django apps
CSRF_COOKIE_SAMESITE = "Lax"  # Changed from "None"

# Read log level from DJANGO_LOG_LEVEL or fall back to generic LOG_LEVEL; default to INFO.
# Logging level configuration
# DJANGO_LOG_LEVEL = os.getenv("DJANGO_LOG_LEVEL", os.getenv("LOG_LEVEL", "INFO"))

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "business_suite.authentication.JwtOrMockAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        # 'rest_framework.permissions.IsAuthenticated', #the one below is more granular
        "rest_framework.permissions.DjangoModelPermissions",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "djangorestframework_camel_case.render.CamelCaseJSONRenderer",
        "djangorestframework_camel_case.render.CamelCaseBrowsableAPIRenderer",
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "djangorestframework_camel_case.parser.CamelCaseJSONParser",
        "djangorestframework_camel_case.parser.CamelCaseFormParser",
        "djangorestframework_camel_case.parser.CamelCaseMultiPartParser",
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
        "rest_framework.parsers.FileUploadParser",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "EXCEPTION_HANDLER": "api.utils.exception_handler.custom_exception_handler",
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/day",
        "user": "1000/day",
        "quick_create": "20/minute",
        "cron": "5/minute",
        "ocr": "10/minute",
        "ocr_status": "120/minute",
        "document_ocr": "10/minute",
        "document_ocr_status": "120/minute",
    },
}

SPECTACULAR_SETTINGS = {
    "TITLE": "BusinessSuite API",
    "DESCRIPTION": "API for BusinessSuite ERP/CRM",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "CAMELIZE_NAMES": True,
    "COMPONENT_SPLIT_PATCH": False,
    # Preprocessing hooks help filter out endpoints that are hard to auto-discover
    # We add a hook that excludes APIView endpoints without serializer declarations
    "PREPROCESSING_HOOKS": ["core.openapi.preprocess_exclude_api_views_without_serializer"],
    "POSTPROCESSING_HOOKS": [
        "core.openapi.postprocess_add_job_id_param",
        "core.openapi.postprocess_add_mock_paths",
    ],
    # ENUM_NAME_OVERRIDES maps a friendly enum name to a choices definition (import path or callable)
    # This avoids drf-spectacular generating many colliding enum names for fields named 'status'.
    "ENUM_NAME_OVERRIDES": {
        # DocApplication and DocWorkflow share the same choices; use a single override name
        "DocApplicationStatus": "customer_applications.models.doc_application.DocApplication.STATUS_CHOICES",
        "InvoiceStatus": "invoices.models.invoice.Invoice.INVOICE_STATUS_CHOICES",
        "InvoicePaymentStatus": "invoices.models.invoice.InvoiceApplication.PAYMENT_STATUS_CHOICES",
        # Consolidate identical job status choices under a single shared enum name to avoid duplication
        "JobStatus": ["queued", "processing", "completed", "failed"],
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    "JTI_CLAIM": "jti",
}

# CORS configuration - read from environment in production
# Preferred env var: CORS_ALLOWED_ORIGINS (comma separated list of origins)
# Fallback defaults include localhost dev ports and the configured APP_DOMAIN
_default_cors_origins = [
    "http://localhost:3000",
    "http://localhost:4200",
]
if APP_DOMAIN:
    _default_cors_origins += [f"https://{APP_DOMAIN}", f"https://admin.{APP_DOMAIN}", f"https://www.{APP_DOMAIN}"]

CORS_ALLOWED_ORIGINS = _parse_list(os.getenv("CORS_ALLOWED_ORIGINS", ",".join(_default_cors_origins)))
# Allow credentials (cookies) only when explicitly enabled in env var (default False for safety)
CORS_ALLOW_CREDENTIALS = _parse_bool(os.getenv("CORS_ALLOW_CREDENTIALS", "False"))
# Ensure common headers (including Authorization) are allowed for preflight requests.
# Use defaults from django-cors-headers and extend if needed.
try:
    from corsheaders.defaults import default_headers
except Exception:  # pragma: no cover - optional package
    CORS_ALLOW_HEADERS = None
else:
    CORS_ALLOW_HEADERS = list(default_headers) + ["authorization"]

CORS_ALLOW_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
# Expose Content-Disposition so the frontend can read filename from responses
try:
    from corsheaders.defaults import default_headers as _default_cors_headers
except Exception:  # pragma: no cover - optional package
    CORS_EXPOSE_HEADERS = ["Content-Disposition"]
else:
    # combine and ensure uniqueness
    CORS_EXPOSE_HEADERS = list(
        {*(getattr(globals().get("CORS_EXPOSE_HEADERS", []), "copy", lambda: [])()), *["Content-Disposition"]}
    )

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# https://github.com/legion-an/django-models-logging
LOGGING_MODELS = (
    # 'app.ClassName',      # logging only for this model
    "customers",  # logging of all models in this app
    "products",
    "invoices",
    "customer_applications",
)

SESSION_SAVE_EVERY_REQUEST = True

# This is for the debug toolbar when using docker
# https://docs.djangoproject.com/en/3.2/ref/settings/#internal-ips
# if DEBUG:
#     import socket  # only if you haven't already imported this
#     hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
#     INTERNAL_IPS = [ip[: ip.rfind(".")] + ".1" for ip in ips] + ["127.0.0.1", "10.0.2.2"]


CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        # "LOCATION": "unique-snowflake",
    },
    "select2": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    },
}

# Content Security Policy support: generate per-request nonces and expose mode
CSP_ENABLED = _parse_bool(os.getenv("CSP_ENABLED", "False"))
CSP_MODE = os.getenv("CSP_MODE", "report-only")  # report-only|enforce

# Configure Huey. Use an in-memory Sqlite DB while running tests to avoid connecting to
# external Postgres at import time (pytest imports Django settings early).
if TESTING:
    from peewee import SqliteDatabase

    huey_database = SqliteDatabase(":memory:")
else:
    huey_database = PostgresqlDatabase(
        os.getenv("DB_NAME"),
        user=os.getenv("DB_USER"),
        password=os.getenv("DB_PASS"),
        host=os.getenv("DB_HOST") or "localhost",
        port=int(os.getenv("DB_PORT")) if os.getenv("DB_PORT") else 5432,
    )

_HUEY_WORKERS = int(os.getenv("HUEY_WORKERS", "2"))
HUEY = {
    "huey_class": "huey.contrib.sql_huey.SqlHuey",
    "name": "business_suite",
    "results": True,
    "immediate": False,
    "database": huey_database,
    "consumer": {
        "workers": _HUEY_WORKERS,
        "worker_type": os.getenv("HUEY_WORKER_TYPE", "thread"),
        "scheduler_interval": 1,
        "check_worker_health": True,
        "health_check_interval": 1,
    },
}

# select2
SELECT2_CACHE_BACKEND = "select2"

USER_AGENTS_CACHE = "default"

# SESSION_ENGINE = "django.contrib.sessions.backends.cache"
# # SESSION_COOKIE_AGE = 60 * 60 * 24  # One day
# SESSION_COOKIE_AGE = 60 * 5 # 5 minutes

TESSERACT_CMD = "/opt/homebrew/bin/tesseract"


# Settings for Django static and media files
DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


def get_dropbox_token():
    # Skip token refresh in development to avoid network issues
    if os.getenv("DJANGO_DEBUG", "False") == "True":
        return None
    try:
        return refresh_dropbox_token(
            os.getenv("DROPBOX_APP_KEY"),
            os.getenv("DROPBOX_APP_SECRET"),
            os.getenv("DROPBOX_OAUTH2_REFRESH_TOKEN"),
        )
    except Exception as e:
        # Log the error and return None to allow Django to start
        import logging

        logger = logging.getLogger(__name__)
        logger.error(f"Failed to refresh Dropbox token: {e}")
        return None


# Storage configuration
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
    "dbbackup": {
        "BACKEND": "storages.backends.dropbox.DropBoxStorage",
        "OPTIONS": {
            "oauth2_access_token": get_dropbox_token(),
            "app_key": os.getenv("DROPBOX_APP_KEY"),
            "app_secret": os.getenv("DROPBOX_APP_SECRET"),
        },
    },
}

# Folders to exclude from media backup
DBBACKUP_EXCLUDE_MEDIA_FODERS = ["tmpfiles"]

FULL_BACKUP_SCHEDULE = "02:00"
CLEAR_CACHE_SCHEDULE = ["03:00"]

# Database retention for audit log DB `LogEntry` objects.
# Default to 14 days; set to 0 or negative to disable automatic pruning.
AUDITLOG_RETENTION_DAYS = int(os.getenv("AUDITLOG_RETENTION_DAYS", "14"))
# Daily schedule for audit log pruning (HH:MM 24h). Set to empty string to disable scheduling.
AUDITLOG_RETENTION_SCHEDULE = os.getenv("AUDITLOG_RETENTION_SCHEDULE", "04:00")

# Conditionally enable the `auditlog` app and its middleware (so the feature can be fully toggled at startup)
if AUDIT_ENABLED:
    # Add auditlog to installed apps if missing
    if "auditlog" not in INSTALLED_APPS:
        INSTALLED_APPS.append("auditlog")

    # Insert middleware after our performance logger if present, otherwise append at the end
    try:
        idx = MIDDLEWARE.index("core.middleware.performance_logger.PerformanceLoggingMiddleware")
        MIDDLEWARE.insert(idx + 1, "auditlog.middleware.AuditlogMiddleware")
    except ValueError:
        if "auditlog.middleware.AuditlogMiddleware" not in MIDDLEWARE:
            MIDDLEWARE.append("auditlog.middleware.AuditlogMiddleware")
else:
    # Explicitly avoid leaving audit middleware or app configured
    if "auditlog" in INSTALLED_APPS:
        INSTALLED_APPS.remove("auditlog")
    if "auditlog.middleware.AuditlogMiddleware" in MIDDLEWARE:
        MIDDLEWARE.remove("auditlog.middleware.AuditlogMiddleware")

# Determine if we are running as backend or task_worker
# Default to 'backend' unless 'run_huey' is in command line or COMPONENT is set.
COMPONENT = os.getenv("COMPONENT")
if not COMPONENT:
    if "run_huey" in sys.argv:
        COMPONENT = "task_worker"
    else:
        COMPONENT = "backend"

# Define the primary handler for this component
PRIMARY_HANDLER = "backend_file" if COMPONENT == "backend" else "task_worker_file"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process} {thread} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "filters": {
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "backend_file": {
            "level": "INFO",
            "class": "concurrent_log_handler.ConcurrentRotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "django.log"),
            "maxBytes": 10 * 1024 * 1024,
            "backupCount": 10,
            "formatter": "verbose",
        },
        "task_worker_file": {
            "level": "INFO",
            "class": "concurrent_log_handler.ConcurrentRotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "task_worker.log"),
            "maxBytes": 10 * 1024 * 1024,
            "backupCount": 10,
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console", PRIMARY_HANDLER],
        "level": "WARNING",
    },
    "loggers": {
        "django": {
            "handlers": ["console", PRIMARY_HANDLER],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },
        "huey": {
            "handlers": ["console", PRIMARY_HANDLER],
            "level": "INFO",
            "propagate": False,
        },
        "performance": {
            "handlers": ["console", PRIMARY_HANDLER],
            "level": "INFO",
            "propagate": False,
        },
        "core": {
            "handlers": ["console", PRIMARY_HANDLER],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Remove the manual loop and use the standard Django logging configuration.
# The Logger service can still be used for ad-hoc loggers.

# Note: Loki-specific attachment of handlers has been removed. Grafana Alloy should
# scrape container stdout/stderr or log files (e.g., `logs/`) to collect logs. If you
# want additional loggers to forward audit events to the file-based fallback handler,
# add "fail_safe_audit" to their handler lists here.
CURRENCY = "IDR"
CURRENCY_SYMBOL = "Rp"
CURRENCY_DECIMAL_PLACES = 0

# OpenAI API configuration for invoice import
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
OPENROUTER_API_BASE_URL = os.getenv("OPENROUTER_API_BASE_URL", "https://openrouter.ai/api/v1")

# LLM Provider: "openrouter" for multi-provider access, "openai" for direct OpenAI API
LLM_PROVIDER = os.getenv("LLM_PROVIDER", "openrouter")
LLM_DEFAULT_MODEL = os.getenv("LLM_DEFAULT_MODEL", "google/gemini-2.5-flash-lite")

# Python 3.14+ Logging Performance Optimizations
# Disable gathering of thread, process, and asyncio information to reduce overhead
logging.logThreads = False
logging.logProcesses = False
logging.logMultiprocessing = False
logging.logAsyncioTasks = False
