"""
Django settings for business_suite project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from .base import *

# Ensure a sane default for document language in development/testing
DEFAULT_DOCUMENT_LANGUAGE_CODE = os.getenv("DEFAULT_DOCUMENT_LANGUAGE_CODE", "id")

CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_DOMAIN = None
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = None
SESSION_COOKIE_DOMAIN = None
CSRF_TRUSTED_ORIGINS = [
    "http://192.168.100.80",
    "https://192.168.100.80",
    "http://localhost:4200",
    "http://127.0.0.1:4200",
]
SESSION_COOKIE_SAMESITE = None
ALLOWED_HOSTS = ["*"]
CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",
    "http://127.0.0.1:4200",
]
CORS_ALLOW_CREDENTIALS = True

# SECURITY WARNING: don't run with debug turned on in production!
# Respect MOCK_AUTH_ENABLED from .env (overriding base default only if explicitly set there)
# If not set in .env, it defaults to what base.py determined.
# We don't hardcode it here to True anymore to allow centralization via .env
MOCK_AUTH_USERNAME = os.getenv("MOCK_AUTH_USERNAME", "stef")
MOCK_AUTH_EMAIL = os.getenv("MOCK_AUTH_EMAIL", "stef@revisbali.com")
MOCK_AUTH_IS_SUPERUSER = True
MOCK_AUTH_IS_STAFF = True

# Avoid exhausting Postgres connection limits during local refreshes.
# Keep connections non-persistent in dev so they close at the end of each request.
DATABASES["default"]["CONN_MAX_AGE"] = 0

# This is to show django-debug-toolbar (https://django-debug-toolbar.readthedocs.io/en/latest/installation.html)
INTERNAL_IPS = [
    "127.0.0.1",
]

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # to serve static files
    "django.contrib.sessions.middleware.SessionMiddleware",
    "business_suite.middlewares.disable_csrf_check.DisableCsrfCheckMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",  # CSRF middleware - REQUIRED
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "business_suite.middlewares.disable_django_views.DisableDjangoViewsMiddleware",
    "business_suite.middlewares.AuthLoginRequiredMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_user_agents.middleware.UserAgentMiddleware",
    "core.middleware.performance_logger.PerformanceLoggingMiddleware",
]

# Keep default/dbbackup storage from base.py (including USE_CLOUD_STORAGE toggle).
# Only relax staticfiles in dev to avoid ManifestStaticFilesStorage requirements.
STORAGES["staticfiles"] = {
    "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
}
STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"
