"""Tighten `CountryCode` identifiers by removing the old implicit id setup.

The migration removes the legacy primary key pattern and adjusts the alpha-3
code field to match the current country code model constraints.
"""

# Generated by Django 4.2.2 on 2023-07-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_enable_pg_trgm"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="countrycode",
            name="id",
        ),
        migrations.AlterField(
            model_name="countrycode",
            name="alpha3_code",
            field=models.CharField(max_length=3, primary_key=True, serialize=False, unique=True),
        ),
    ]
