"""
FILE_ROLE: Django migration for the core app.

KEY_COMPONENTS:
- Migration: Module symbol.

INTERACTIONS:
- Depends on: core app schema/runtime machinery and adjacent services imported by this module.

AI_GUIDELINES:
- Keep command logic thin and delegate real work to services when possible.
- Keep migrations schema-only and reversible; do not add runtime business logic here.
"""

# Generated by Django 6.0.1 on 2026-01-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_ocr_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocrjob",
            name="traceback",
            field=models.TextField(blank=True),
        ),
    ]
