# Generated by Django 6.0.1 on 2026-01-17 08:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ocrjob_traceback'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentOCRJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('request_params', models.JSONField(blank=True, default=dict)),
                ('result_text', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('traceback', models.TextField(blank=True)),
                ('file_path', models.CharField(blank=True, max_length=512)),
                ('file_url', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
