# Generated by Django 6.0.2 on 2026-02-13 14:05

import core.models.calendar_event
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_web_push_subscription'),
        ('customer_applications', '0010_workflownotification_type_and_target_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.CharField(default=core.models.calendar_event._default_calendar_event_id, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('application', 'Application')], db_index=True, default='manual', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('attendees', models.JSONField(blank=True, default=list)),
                ('notifications', models.JSONField(blank=True, default=dict)),
                ('extended_properties', models.JSONField(blank=True, default=dict)),
                ('color_id', models.CharField(blank=True, max_length=2, null=True)),
                ('google_calendar_id', models.CharField(blank=True, default='', max_length=255)),
                ('google_event_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('sync_error', models.TextField(blank=True, default='')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='customer_applications.docapplication')),
            ],
            options={
                'ordering': ['-start_date', '-start_time', '-created_at'],
                'indexes': [models.Index(fields=['application', 'source'], name='calevent_app_source_idx'), models.Index(fields=['sync_status', 'updated_at'], name='calevent_sync_status_idx')],
            },
        ),
    ]
