# Generated by Django 6.0.2 on 2026-02-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_calendarevent_application_cascade'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequestUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(db_index=True, max_length=120)),
                ('provider', models.CharField(db_index=True, max_length=32)),
                ('model', models.CharField(db_index=True, max_length=160)),
                ('request_type', models.CharField(db_index=True, default='chat.completions', max_length=32)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('success', models.BooleanField(db_index=True, default=True)),
                ('error_type', models.CharField(blank=True, max_length=64)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('completion_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('total_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('cached_prompt_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('cache_write_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('reasoning_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['feature', 'created_at'], name='core_airequ_feature_042eb4_idx'), models.Index(fields=['provider', 'created_at'], name='core_airequ_provide_2973dd_idx'), models.Index(fields=['model', 'created_at'], name='core_airequ_model_a63589_idx')],
            },
        ),
    ]
