"""
FILE_ROLE: Django migration for the core app.

KEY_COMPONENTS:
- Migration: Module symbol.

INTERACTIONS:
- Depends on: core app schema/runtime machinery and adjacent services imported by this module.

AI_GUIDELINES:
- Keep command logic thin and delegate real work to services when possible.
- Keep migrations schema-only and reversible; do not add runtime business logic here.
"""

# Generated by Django 6.0.2 on 2026-02-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_calendarreminder"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarreminder",
            name="read_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
