# Generated by Django 6.0.2 on 2026-02-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_calendarreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarreminder',
            name='read_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
