# Generated by Django 6.0.2 on 2026-02-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_calendarreminder_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarreminder',
            name='delivery_channel',
            field=models.CharField(blank=True, choices=[('in_app', 'In-App'), ('system', 'System Notification')], db_index=True, default='', max_length=16),
        ),
    ]
