# Generated by Django 6.0.2 on 2026-02-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_ocr_jobs_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cache_enabled',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether caching is enabled for this user. When disabled, all cache operations are bypassed.'),
        ),
    ]
