# Generated by Codex on 2026-02-25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_add_cache_enabled_to_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalResilienceSettings",
            fields=[
                (
                    "singleton_key",
                    models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("encryption_required", models.BooleanField(default=True)),
                (
                    "desktop_mode",
                    models.CharField(
                        choices=[("local_primary", "Local Primary"), ("remote_primary", "Remote Primary")],
                        default="local_primary",
                        max_length=32,
                    ),
                ),
                ("vault_epoch", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_local_resilience_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Local Resilience Settings",
                "verbose_name_plural": "Local Resilience Settings",
            },
        ),
        migrations.CreateModel(
            name="MediaManifestEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("path", models.CharField(max_length=512, unique=True)),
                ("checksum", models.CharField(max_length=64)),
                ("size", models.BigIntegerField(default=0)),
                ("modified_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("encrypted", models.BooleanField(default=True)),
                ("storage_backend", models.CharField(blank=True, default="", max_length=255)),
                ("source_node", models.CharField(blank=True, default="", max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["path"],
            },
        ),
        migrations.CreateModel(
            name="SyncChangeLog",
            fields=[
                ("seq", models.BigAutoField(primary_key=True, serialize=False)),
                ("source_node", models.CharField(db_index=True, max_length=64)),
                ("model_label", models.CharField(db_index=True, max_length=128)),
                ("object_pk", models.CharField(db_index=True, max_length=128)),
                ("operation", models.CharField(choices=[("upsert", "Upsert"), ("delete", "Delete")], max_length=16)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("source_timestamp", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("checksum", models.CharField(blank=True, default="", max_length=64)),
                ("applied", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["seq"],
            },
        ),
        migrations.CreateModel(
            name="SyncConflict",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("model_label", models.CharField(db_index=True, max_length=128)),
                ("object_pk", models.CharField(db_index=True, max_length=128)),
                ("incoming_change", models.JSONField(blank=True, default=dict)),
                ("existing_snapshot", models.JSONField(blank=True, default=dict)),
                ("chosen_source", models.CharField(default="existing", max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("reviewed", "Reviewed")],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SyncCursor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("node_id", models.CharField(max_length=64, unique=True)),
                ("last_pulled_seq", models.BigIntegerField(default=0)),
                ("last_pushed_seq", models.BigIntegerField(default=0)),
                ("last_pulled_at", models.DateTimeField(blank=True, null=True)),
                ("last_pushed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["node_id"],
            },
        ),
        migrations.AddIndex(
            model_name="mediamanifestentry",
            index=models.Index(fields=["updated_at", "path"], name="mediamani_updated_path_idx"),
        ),
        migrations.AddIndex(
            model_name="syncchangelog",
            index=models.Index(fields=["model_label", "object_pk", "seq"], name="syncchg_model_obj_seq_idx"),
        ),
        migrations.AddIndex(
            model_name="syncchangelog",
            index=models.Index(fields=["source_node", "seq"], name="syncchg_src_seq_idx"),
        ),
        migrations.AddIndex(
            model_name="syncchangelog",
            index=models.Index(fields=["source_timestamp", "seq"], name="syncchg_ts_seq_idx"),
        ),
    ]
