"""
FILE_ROLE: Django migration for the core app.

KEY_COMPONENTS:
- Migration: Module symbol.

INTERACTIONS:
- Depends on: core app schema/runtime machinery and adjacent services imported by this module.

AI_GUIDELINES:
- Keep command logic thin and delegate real work to services when possible.
- Keep migrations schema-only and reversible; do not add runtime business logic here.
"""

# Generated by Django 6.0.2 on 2026-02-26 08:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_local_resilience_sync_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarreminder",
            name="sent_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="calendarreminder",
            index=models.Index(fields=["user", "status", "sent_at"], name="calrem_usr_st_sent_idx"),
        ),
        migrations.AddIndex(
            model_name="calendarreminder",
            index=models.Index(fields=["user", "status", "sent_at", "read_at"], name="calrem_usr_st_sr_rd_idx"),
        ),
    ]
