# Generated by Django 6.0.2 on 2026-02-27 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_calendarreminder_sent_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UiSettings',
            fields=[
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('use_overlay_menu', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_ui_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UI Settings',
                'verbose_name_plural': 'UI Settings',
            },
        ),
    ]
