# Generated by Django 6.0.2 on 2026-03-04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _serialize_value(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (list, tuple)):
        return ",".join(str(item).strip() for item in value if str(item).strip())
    return str(value)


def seed_ai_runtime_settings(apps, schema_editor):
    AppSetting = apps.get_model("core", "AppSetting")

    llm_default_model = str(getattr(settings, "LLM_DEFAULT_MODEL", "google/gemini-3-flash-preview") or "").strip()
    if not llm_default_model:
        llm_default_model = "google/gemini-3-flash-preview"

    defaults = {
        "LLM_PROVIDER": str(getattr(settings, "LLM_PROVIDER", "openrouter") or "openrouter").strip().lower(),
        "LLM_DEFAULT_MODEL": llm_default_model,
        "GROQ_DEFAULT_MODEL": (
            str(getattr(settings, "GROQ_DEFAULT_MODEL", "meta-llama/llama-4-scout-17b-16e-instruct") or "").strip()
            or "meta-llama/llama-4-scout-17b-16e-instruct"
        ),
        "OPENROUTER_DEFAULT_MODEL": (
            str(getattr(settings, "OPENROUTER_DEFAULT_MODEL", "google/gemini-2.5-flash-lite") or "").strip()
            or "google/gemini-2.5-flash-lite"
        ),
        "OPENAI_DEFAULT_MODEL": (
            str(getattr(settings, "OPENAI_DEFAULT_MODEL", "gpt-5-mini") or "").strip() or "gpt-5-mini"
        ),
        "INVOICE_IMPORT_MODEL": "",
        "PASSPORT_OCR_MODEL": "",
        "DOCUMENT_CATEGORIZER_MODEL": "",
        "DOCUMENT_CATEGORIZER_MODEL_HIGH": "",
        "DOCUMENT_VALIDATOR_MODEL": "",
        "DOCUMENT_OCR_STRUCTURED_MODEL": "",
        "CHECK_PASSPORT_MODEL": "",
        "CHECK_PASSPORT_AI_MIN_CONFIDENCE_FOR_UPLOAD": float(
            getattr(settings, "CHECK_PASSPORT_AI_MIN_CONFIDENCE_FOR_UPLOAD", 0.95)
        ),
        "LLM_AUTO_FALLBACK_ENABLED": bool(getattr(settings, "LLM_AUTO_FALLBACK_ENABLED", True)),
        "LLM_FALLBACK_PROVIDER_ORDER": list(getattr(settings, "LLM_FALLBACK_PROVIDER_ORDER", [])),
        "LLM_FALLBACK_STICKY_SECONDS": int(getattr(settings, "LLM_FALLBACK_STICKY_SECONDS", 3600)),
        "LLM_FALLBACK_STICKY_CACHE_KEY": (
            str(getattr(settings, "LLM_FALLBACK_STICKY_CACHE_KEY", "ai:router:sticky_provider") or "").strip()
            or "ai:router:sticky_provider"
        ),
        "OPENROUTER_API_BASE_URL": (
            str(getattr(settings, "OPENROUTER_API_BASE_URL", "https://openrouter.ai/api/v1") or "").strip()
            or "https://openrouter.ai/api/v1"
        ),
        "OPENROUTER_TIMEOUT": float(getattr(settings, "OPENROUTER_TIMEOUT", 120.0)),
        "OPENAI_TIMEOUT": float(getattr(settings, "OPENAI_TIMEOUT", 120.0)),
    }

    descriptions = {
        "LLM_PROVIDER": "Primary LLM provider.",
        "LLM_DEFAULT_MODEL": "Global default model for non-groq providers.",
        "GROQ_DEFAULT_MODEL": "Default model used when provider is Groq.",
        "OPENROUTER_DEFAULT_MODEL": "Provider-specific default model for OpenRouter.",
        "OPENAI_DEFAULT_MODEL": "Provider-specific default model for OpenAI direct API.",
        "INVOICE_IMPORT_MODEL": "Workflow-specific model for invoice import AI parser.",
        "PASSPORT_OCR_MODEL": "Workflow-specific model for passport OCR AI extractor.",
        "DOCUMENT_CATEGORIZER_MODEL": "Primary model for document categorization pass-1.",
        "DOCUMENT_CATEGORIZER_MODEL_HIGH": "Fallback model for document categorization pass-2.",
        "DOCUMENT_VALIDATOR_MODEL": "Model for document validation rules.",
        "DOCUMENT_OCR_STRUCTURED_MODEL": "Model for structured OCR extraction.",
        "CHECK_PASSPORT_MODEL": "Model for passport uploadability checks.",
        "CHECK_PASSPORT_AI_MIN_CONFIDENCE_FOR_UPLOAD": "Minimum AI confidence threshold for passport uploadability acceptance.",
        "LLM_AUTO_FALLBACK_ENABLED": "Enable automatic provider failover on retriable errors.",
        "LLM_FALLBACK_PROVIDER_ORDER": "Comma-separated provider order used for failover.",
        "LLM_FALLBACK_STICKY_SECONDS": "Sticky failover provider TTL in seconds.",
        "LLM_FALLBACK_STICKY_CACHE_KEY": "Cache key used to persist sticky failover provider.",
        "OPENROUTER_API_BASE_URL": "OpenRouter API base URL.",
        "OPENROUTER_TIMEOUT": "OpenRouter API timeout in seconds.",
        "OPENAI_TIMEOUT": "OpenAI API timeout in seconds.",
    }

    for name, default_value in defaults.items():
        AppSetting.objects.get_or_create(
            name=name,
            defaults={
                "value": _serialize_value(default_value),
                "scope": "backend",
                "description": descriptions.get(name, ""),
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_uisettings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(db_index=True, max_length=120, unique=True)),
                ("value", models.TextField(blank=True, default="")),
                (
                    "scope",
                    models.CharField(
                        choices=[("backend", "Backend"), ("frontend", "Frontend"), ("both", "Frontend + Backend")],
                        default="backend",
                        max_length=16,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_app_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Application Setting",
                "verbose_name_plural": "Application Settings",
                "ordering": ("name",),
            },
        ),
        migrations.RunPython(seed_ai_runtime_settings, reverse_code=migrations.RunPython.noop),
    ]
