# Generated by Django 6.0.3 on 2026-03-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_appsetting_is_runtime_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='architecture_modality',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='architecture_tokenizer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='instruct_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='max_requests_per_minute',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='per_request_limits',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='prompt_cache_write_price_per_token',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='prompt_cached_price_per_token',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='provider_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='requests_per_minute',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='supported_parameters',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='tokens_per_minute',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='top_provider_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
