"""
FILE_ROLE: Django migration for the core app.

KEY_COMPONENTS:
- Migration: Module symbol.

INTERACTIONS:
- Depends on: core app schema/runtime machinery and adjacent services imported by this module.

AI_GUIDELINES:
- Keep command logic thin and delegate real work to services when possible.
- Keep migrations schema-only and reversible; do not add runtime business logic here.
"""

# Generated by Django 6.0.3 on 2026-03-08 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_add_aimodel_extended_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aimodel",
            name="max_requests_per_minute",
        ),
        migrations.RemoveField(
            model_name="aimodel",
            name="requests_per_minute",
        ),
        migrations.RemoveField(
            model_name="aimodel",
            name="tokens_per_minute",
        ),
    ]
