"""Remove the cached pricing field from the AI model registry.

This migration drops stale pricing storage now that pricing is computed from
current runtime sources instead of persisted cache.
"""

# Generated by Django 6.0.3 on 2026-03-08 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_remove_aimodel_rate_limits"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aimodel",
            name="prompt_cache_write_price_per_token",
        ),
        migrations.RemoveField(
            model_name="aimodel",
            name="prompt_cached_price_per_token",
        ),
    ]
