# Generated by Django 6.0.3 on 2026-03-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_aimodel_cached_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='model_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
