"""Allow the AI model identifier to be optional.

The migration relaxes the AI model registry so partially defined records can be
stored during setup or synchronization flows.
"""

# Generated by Django 6.0.3 on 2026-03-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_remove_aimodel_cached_pricing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodel",
            name="model_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
