# Generated by Django 6.0.3 on 2026-03-27 00:28

from django.db import migrations


def seed_initial_rules(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    RbacMenuRule = apps.get_model("core", "RbacMenuRule")
    RbacFieldRule = apps.get_model("core", "RbacFieldRule")

    try:
        admin_group = Group.objects.get(name="admin")
    except Group.DoesNotExist:
        admin_group = None

    try:
        manager_group = Group.objects.get(name="manager")
    except Group.DoesNotExist:
        manager_group = None

    # 1. Restrict 'products' menu: Hidden for Everyone by default, Visible for Admin & Manager
    RbacMenuRule.objects.create(group=None, menu_id="products", is_visible=False)
    if admin_group:
        RbacMenuRule.objects.create(group=admin_group, menu_id="products", is_visible=True)
    if manager_group:
        RbacMenuRule.objects.create(group=manager_group, menu_id="products", is_visible=True)

    # 2. Restrict 'base_price' field on 'product': Hidden/Readonly by default, RW for Admin & Manager
    RbacFieldRule.objects.create(
        group=None, model_name="product", field_name="base_price", can_read=False, can_write=False
    )
    if admin_group:
        RbacFieldRule.objects.create(
            group=admin_group, model_name="product", field_name="base_price", can_read=True, can_write=True
        )
    if manager_group:
        RbacFieldRule.objects.create(
            group=manager_group, model_name="product", field_name="base_price", can_read=True, can_write=True
        )


def reverse_initial_rules(apps, schema_editor):
    RbacMenuRule = apps.get_model("core", "RbacMenuRule")
    RbacFieldRule = apps.get_model("core", "RbacFieldRule")

    RbacMenuRule.objects.filter(menu_id="products").delete()
    RbacFieldRule.objects.filter(model_name="product", field_name="base_price").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_rbacfieldrule_rbacmenurule'),
    ]

    operations = [
        migrations.RunPython(seed_initial_rules, reverse_initial_rules),
    ]
