# Generated by Django 6.0.3 on 2026-03-27 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0035_seed_rbac_rules'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rbacfieldrule',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='rbacmenurule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rbacfieldrule',
            name='role',
            field=models.CharField(blank=True, choices=[('is_staff', 'Staff Status (is_staff)'), ('is_superuser', 'Superuser Status (is_superuser)')], help_text='Optional: Apply this rule only to users with this specific Django role.', max_length=50),
        ),
        migrations.AddField(
            model_name='rbacmenurule',
            name='role',
            field=models.CharField(blank=True, choices=[('is_staff', 'Staff Status (is_staff)'), ('is_superuser', 'Superuser Status (is_superuser)')], help_text='Optional: Apply this rule only to users with this specific Django role.', max_length=50),
        ),
        migrations.AlterField(
            model_name='rbacfieldrule',
            name='group',
            field=models.ForeignKey(blank=True, help_text='If blank, applies to all authenticated users (unless overridden by role).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_rules', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='rbacmenurule',
            name='group',
            field=models.ForeignKey(blank=True, help_text='If blank, applies to all authenticated users (unless overridden by role).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_rules', to='auth.group'),
        ),
        migrations.AlterUniqueTogether(
            name='rbacfieldrule',
            unique_together={('group', 'role', 'model_name', 'field_name')},
        ),
        migrations.AlterUniqueTogether(
            name='rbacmenurule',
            unique_together={('group', 'role', 'menu_id')},
        ),
    ]
