# Generated by Django 4.2.1 on 2023-05-31 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='documents_min_validity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
