# Generated by Django 4.2.2 on 2023-06-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_documents_min_validity'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duration_is_business_days',
            field=models.BooleanField(default=True),
        ),
    ]
