# Generated by Django 4.2.1 on 2023-05-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_type_product_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='required_documents',
        ),
        migrations.AddField(
            model_name='product',
            name='required_documents',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
