# Generated by Django 4.2.2 on 2023-06-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_documenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
