# Generated by Django 4.2.1 on 2023-05-25 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_task_notify_days_before_alter_product_base_price_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('product', 'step')},
        ),
    ]
