# Generated by Django 4.2.2 on 2023-06-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_product_name_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='notify_days_before',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
