# Generated by Django 4.2.2 on 2023-06-13 10:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_documenttype_doc_number_regex"),
    ]

    operations = [
        migrations.RenameField(
            model_name="documenttype",
            old_name="doc_number_regex",
            new_name="validation_rule_regex",
        ),
    ]
