# Generated by Django 4.2.2 on 2023-06-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_rename_doc_number_regex_documenttype_validation_rule_regex"),
    ]

    operations = [
        migrations.AddField(
            model_name="documenttype",
            name="is_in_required_documents",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="template",
            field=models.FileField(blank=True, upload_to="templates/"),
        ),
    ]
