# Generated by Django 4.2.2 on 2023-06-20 03:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0011_documenttype_is_in_required_documents_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documenttype",
            name="template",
        ),
        migrations.AddField(
            model_name="documenttype",
            name="print_template",
            field=models.TextField(blank=True),
        ),
    ]
