# Generated by Django 4.2.2 on 2023-06-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0012_remove_documenttype_template_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documenttype",
            name="print_template",
        ),
        migrations.AddField(
            model_name="product",
            name="optional_documents",
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
