# Generated by Django 4.2.2 on 2023-06-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0013_remove_documenttype_print_template_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="immigration_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
